const Grade3 = [
  {
    kanji: "事",
    kun: "こと, つか. う, つか. える",
    on: "ジ, ズ",
    meaning: "Matter, thing, fact, business, reason, possibly",
  },
  {
    kanji: "発",
    kun: "た. つ, あば. く, おこ. る, つか. わす, はな. つ",
    on: "ハツ, ホツ",
    meaning:
      "Discharge, departure, publish, emit, start from, disclose, counter for gunshots",
  },
  {
    kanji: "者",
    kun: "もの",
    on: "シャ",
    meaning: "Someone, person",
  },
  {
    kanji: "業",
    kun: "わざ",
    on: "ギョウ, ゴウ",
    meaning: "Business, vocation, arts, performance",
  },
  {
    kanji: "員",
    on: "イン",
    meaning: "Employee, member, number, the one in charge",
  },
  {
    kanji: "開",
    kun: "ひら. く, ひら. き, -びら. き, ひら. ける, あ. く",
    on: "カイ",
    meaning: "Open, unfold, unseal",
  },
  {
    kanji: "問",
    kun: "と. う, と. い, とん",
    on: "モン",
    meaning: "Question, ask, problem",
  },
  {
    kanji: "代",
    kun: "か. わる, かわ. る, かわ. り, -がわ. り, か. える",
    on: "ダイ, タイ",
    meaning:
      "Substitute, change, convert, replace, period, age, counter for decades of ages, eras, etc., generation, charge, rate, fee",
  },
  {
    kanji: "動",
    kun: "うご. く, うご. かす",
    on: "ドウ",
    meaning: "Move, motion, change, confusion, shift, shake",
  },
  {
    kanji: "主",
    kun: "ぬし, おも, あるじ",
    on: "シュ, ス, シュウ",
    meaning: "Lord, chief, master, main thing, principal",
  },
  {
    kanji: "題",
    on: "ダイ",
    meaning: "Topic, subject",
  },
  {
    kanji: "意",
    on: "イ",
    meaning: "Idea, mind, heart, taste, thought, desire, care, liking",
  },
  {
    kanji: "度",
    kun: "たび, -た. い",
    on: "ド, ト, タク",
    meaning: "Degrees, occurrence, time, counter for occurrences",
  },
  {
    kanji: "持",
    kun: "も. つ, -も. ち, も. てる",
    on: "ジ",
    meaning: "Hold, have",
  },
  {
    kanji: "世",
    kun: "よ, さんじゅう",
    on: "セイ, セ, ソウ",
    meaning: "Generation, world, society, public",
  },
  {
    kanji: "安",
    kun: "やす. い, やす. まる, やす, やす. らか",
    on: "アン",
    meaning: "Relax, cheap, low, quiet, rested, contented, peaceful",
  },
  {
    kanji: "院",
    on: "イン",
    meaning: "Institution, temple, mansion, school",
  },
  {
    kanji: "界",
    on: "カイ",
    meaning: "World",
  },
  {
    kanji: "重",
    kun: "え, おも. い, おも. り, おも. なう, かさ. ねる",
    on: "ジュウ, チョウ",
    meaning: "Heavy, heap up, pile up, nest of boxes",
  },
  {
    kanji: "集",
    kun: "あつ. まる, あつ. める, つど. う",
    on: "シュウ",
    meaning: "Gather, meet, congregate, swarm, flock",
  },
  {
    kanji: "物",
    kun: "もの, もの-",
    on: "ブツ, モツ",
    meaning: "Thing, object, matter",
  },
  {
    kanji: "使",
    kun: "つか. う, つか. い, -つか. い, -づか. い",
    on: "シ",
    meaning: "Use",
  },
  {
    kanji: "品",
    kun: "しな",
    on: "ヒン, ホン",
    meaning: "Goods, refinement, dignity, article, counter for meal courses",
  },
  {
    kanji: "死",
    kun: "し. ぬ, し. に-",
    on: "シ",
    meaning: "Death, die",
  },
  {
    kanji: "始",
    kun: "はじ. める, -はじ. める, はじ. まる",
    on: "シ",
    meaning: "Commence, begin",
  },
  {
    kanji: "運",
    kun: "はこ. ぶ",
    on: "ウン",
    meaning: "Carry, luck, destiny, fate, lot, transport, progress, advance",
  },
  {
    kanji: "終",
    kun: "お. わる, -お. わる, おわ. る, お. える, つい",
    on: "シュウ",
    meaning: "End, finish",
  },
  {
    kanji: "住",
    kun: "す. む, す. まう, -ず. まい",
    on: "ジュウ, ヂュウ, チュウ",
    meaning: "Dwell, reside, live, inhabit",
  },
  {
    kanji: "真",
    kun: "ま, ま-, まこと",
    on: "シン",
    meaning: "True, reality, Buddhist sect",
  },
  {
    kanji: "有",
    kun: "あ. る",
    on: "ユウ, ウ",
    meaning: "Possess, have, exist, happen, occur, approx",
  },
  {
    kanji: "急",
    kun: "いそ. ぐ, いそ. ぎ",
    on: "キュウ",
    meaning: "Hurry, emergency, sudden, steep",
  },
  {
    kanji: "送",
    kun: "おく. る",
    on: "ソウ",
    meaning: "Escort, send",
  },
  {
    kanji: "転",
    kun: "ころ. がる, ころ. げる, ころ. がす, ころ. ぶ",
    on: "テン",
    meaning: "Revolve, turn around, change",
  },
  {
    kanji: "研",
    kun: "と. ぐ",
    on: "ケン",
    meaning: "Polish, study of, sharpen",
  },
  {
    kanji: "究",
    kun: "きわ. める",
    on: "キュウ, ク",
    meaning: "Research, study",
  },
  {
    kanji: "起",
    kun: "お. きる, お. こる, お. こす, おこ. す, た. つ",
    on: "キ",
    meaning: "Rouse, wake up, get up",
  },
  {
    kanji: "着",
    kun: "き. る, -ぎ, き. せる, -き. せ, つ. く, つ. ける",
    on: "チャク, ジャク",
    meaning: "Arrive, wear, counter for suits of clothing",
  },
  {
    kanji: "病",
    kun: "や. む, -や. み, やまい",
    on: "ビョウ, ヘイ",
    meaning: "Ill, sick",
  },
  {
    kanji: "待",
    kun: "ま. つ, -ま. ち",
    on: "タイ",
    meaning: "Wait, depend on",
  },
  {
    kanji: "族",
    on: "ゾク",
    meaning: "Tribe, family",
  },
  {
    kanji: "銀",
    kun: "しろがね",
    on: "ギン",
    meaning: "Silver",
  },
  {
    kanji: "医",
    kun: "い. やす, い. する, くすし",
    on: "イ",
    meaning: "Doctor, medicine",
  },
  {
    kanji: "仕",
    kun: "つか. える",
    on: "シ, ジ",
    meaning: "Attend, doing, official, serve",
  },
  {
    kanji: "去",
    kun: "さ. る, -さ. る",
    on: "キョ, コ",
    meaning: "Gone, past, quit, leave, elapse, eliminate, divorce",
  },
  {
    kanji: "味",
    kun: "あじ, あじ. わう",
    on: "ミ",
    meaning: "Flavor, taste",
  },
  {
    kanji: "写",
    kun: "うつ. す, うつ. る, うつ-, うつ. し",
    on: "シャ, ジャ",
    meaning: "Copy, be photographed, describe",
  },
  {
    kanji: "注",
    kun: "そそ. ぐ, さ. す, つ. ぐ",
    on: "チュウ",
    meaning:
      "Pour, irrigate, shed (tears), flow into, concentrate on, notes, comment, annotate",
  },
  {
    kanji: "悪",
    kun: "わる. い, わる-, あ. し, にく. い, -にく. い",
    on: "アク, オ",
    meaning: "Bad, vice, rascal, false, evil, wrong",
  },
  {
    kanji: "館",
    kun: "やかた, たて",
    on: "カン",
    meaning: "Building, mansion, large building, palace",
  },
  {
    kanji: "屋",
    kun: "や",
    on: "オク",
    meaning: "Roof, house, shop, dealer, seller",
  },
  {
    kanji: "対",
    kun: "あいて, こた. える, そろ. い, つれあ. い, なら. ぶ",
    on: "タイ, ツイ",
    meaning: "Opposite, even, equal, versus, anti-, compare",
  },
  {
    kanji: "部",
    kun: "-べ",
    on: "ブ",
    meaning:
      "Section, bureau, dept, class, copy, part, portion, counter for copies of a newspaper or magazine",
  },
  {
    kanji: "相",
    kun: "あい-",
    on: "ソウ, ショウ",
    meaning:
      "inter-, mutual, together, each other, minister of state, councillor, aspect, phase, physiognomy",
  },
  {
    kanji: "定",
    kun: "さだ. める, さだ. まる, さだ. か",
    on: "テイ, ジョウ",
    meaning: "Determine, fix, establish, decide",
  },
  {
    kanji: "実",
    kun: "み, みの. る, まこと, まことに, みの, み ち. る",
    on: "ジツ, シツ",
    meaning: "Reality, truth",
  },
  {
    kanji: "決",
    kun: "き. める, -ぎ. め, き. まる, さ. く",
    on: "ケツ",
    meaning: "Decide, fix, agree upon, appoint",
  },
  {
    kanji: "全",
    kun: "まった. く, すべ. て",
    on: "ゼン",
    meaning: "Whole, entire, all, complete, fulfill",
  },
  {
    kanji: "表",
    kun: "おもて, -おもて, あらわ. す, あらわ. れる",
    on: "ヒョウ",
    meaning: "Surface, table, chart, diagram",
  },
  {
    kanji: "習",
    kun: "なら. う, なら. い",
    on: "シュウ, ジュ",
    meaning: "Learn",
  },
  {
    kanji: "調",
    kun: "しら. べる, しら. べ, ととの. う, ととの. える",
    on: "チョウ",
    meaning:
      "Tune, tone, meter, key (music), writing style, prepare, exorcise, investigate",
  },
  {
    kanji: "化",
    kun: "ば. ける, ば. かす, ふ. ける, け. する",
    on: "カ, ケ",
    meaning:
      "Change, take the form of, influence, enchant, delude, -ization, -ification",
  },
  {
    kanji: "駅",
    on: "エキ",
    meaning: "Station",
  },
  {
    kanji: "期",
    on: "キ, ゴ",
    meaning: "Period, time, date, term",
  },
  {
    kanji: "取",
    kun: "と. る, と. り, と. り-, とり, -ど. り",
    on: "シュ",
    meaning: "Take, fetch, take up",
  },
  {
    kanji: "都",
    kun: "みやこ",
    on: "ト, ツ",
    meaning: "Metropolis, capital",
  },
  {
    kanji: "和",
    kun: "やわ. らぐ, やわ. らげる, なご. む, なご. やか",
    on: "ワ, オ, カ",
    meaning: "Harmony, Japanese style, peace, soften, Japan",
  },
  {
    kanji: "平",
    kun: "たい. ら, -だいら, ひら, ひら-",
    on: "ヘイ, ビョウ, ヒョウ",
    meaning: "Even, flat, peace",
  },
  {
    kanji: "受",
    kun: "う. ける, -う. け, う. かる",
    on: "ジュ",
    meaning: "Accept, undergo, answer (phone), take, get, catch, receive",
  },
  {
    kanji: "区",
    on: "ク, オウ, コウ",
    meaning: "Ward, district",
  },
  {
    kanji: "洋",
    on: "ヨウ",
    meaning: "Ocean, western style",
  },
  {
    kanji: "県",
    kun: "か. ける",
    on: "ケン",
    meaning: "Prefecture",
  },
  {
    kanji: "進",
    kun: "すす. む, すす. める",
    on: "シン",
    meaning: "Advance, proceed, progress, promote",
  },
  {
    kanji: "指",
    kun: "ゆび, さ. す, -さ. し",
    on: "シ",
    meaning:
      "Finger, point to, indicate, put into, play (chess), measure (ruler)",
  },
  {
    kanji: "旅",
    kun: "たび",
    on: "リョ",
    meaning: "Trip, travel",
  },
  {
    kanji: "予",
    kun: "あらかじ. め",
    on: "ヨ, シャ",
    meaning: "Beforehand, previous, myself, I",
  },
  {
    kanji: "向",
    kun: "む. く, む. い, -む. き, む. ける, -む. け",
    on: "コウ",
    meaning: "Yonder, facing, beyond, confront, defy, tend toward, approach",
  },
  {
    kanji: "勝",
    kun: "か. つ, -が. ち, まさ. る, すぐ. れる, かつ",
    on: "ショウ",
    meaning: "Victory, win, prevail, excel",
  },
  {
    kanji: "面",
    kun: "おも, おもて, つら",
    on: "メン, ベン",
    meaning: "Mask, face, features, surface",
  },
  {
    kanji: "委",
    kun: "ゆだ. ねる",
    on: "イ",
    meaning: "Committee, entrust to, leave to, devote, discard",
  },
  {
    kanji: "反",
    kun: "そ. る, そ. らす, かえ. す, かえ. る, -かえ. る",
    on: "ハン, ホン, タン, ホ",
    meaning: "Anti-",
  },
  {
    kanji: "所",
    kun: "ところ, -ところ, どころ, とこ",
    on: "ショ",
    meaning: "Place",
  },
  {
    kanji: "次",
    kun: "つ. ぐ, つぎ",
    on: "ジ, シ",
    meaning: "Next, order, sequence",
  },
  {
    kanji: "係",
    kun: "かか. る, かかり, -がかり, かか. わる",
    on: "ケイ",
    meaning: "Person in charge, connection, duty, concern oneself",
  },
  {
    kanji: "感",
    on: "カン",
    meaning: "Emotion, feeling, sensation",
  },
  {
    kanji: "投",
    kun: "な. げる, -な. げ",
    on: "トウ",
    meaning:
      "Throw, discard, abandon, launch into, join, invest in, hurl, give up, sell at a loss",
  },
  {
    kanji: "打",
    kun: "う. つ, う. ち-, ぶ. つ",
    on: "ダ, ダアス",
    meaning: "Strike, hit, knock, pound, dozen",
  },
  {
    kanji: "島",
    kun: "しま",
    on: "トウ",
    meaning: "Island",
  },
  {
    kanji: "両",
    kun: "てる, ふたつ",
    on: "リョウ",
    meaning:
      "Both, old Japanese coin, counter for carriages (e.g., in a train), two",
  },
  {
    kanji: "服",
    on: "フク",
    meaning: "Clothing, admit, obey, discharge",
  },
  {
    kanji: "式",
    on: "シキ",
    meaning:
      "Style, ceremony, rite, function, method, system, form, expression",
  },
  {
    kanji: "談",
    on: "ダン",
    meaning: "Discuss, talk",
  },
  {
    kanji: "流",
    kun: "なが. れる, なが. れ, なが. す, -なが. す",
    on: "リュウ, ル",
    meaning: "Current, a sink, flow, forfeit",
  },
  {
    kanji: "局",
    kun: "つぼね",
    on: "キョク",
    meaning:
      "Bureau, board, office, affair, conclusion, court lady, lady?in?waiting, her apartment",
  },
  {
    kanji: "放",
    kun: "はな. す, -っぱな. し, はな. つ, はな. れる, こ. く",
    on: "ホウ",
    meaning: "Set free, release, fire, shoot, emit, banish, liberate",
  },
  {
    kanji: "球",
    kun: "たま",
    on: "キュウ",
    meaning: "Ball, sphere",
  },
  {
    kanji: "役",
    on: "ヤク, エキ",
    meaning: "Duty, war, campaign, drafted labor, office, service, role",
  },
  {
    kanji: "身",
    kun: "み",
    on: "シン",
    meaning: "Somebody, person, one’s station in life",
  },
  {
    kanji: "由",
    kun: "よし, よ. る",
    on: "ユ, ユウ, ユイ",
    meaning: "Wherefore, a reason",
  },
  {
    kanji: "飲",
    kun: "の. む, -の. み",
    on: "イン, オン",
    meaning: "Drink, smoke, take",
  },
  {
    kanji: "消",
    kun: "き. える, け. す",
    on: "ショウ",
    meaning: "Extinguish, blow out, turn off, neutralize, cancel",
  },
  {
    kanji: "神",
    kun: "かみ, かん-, こう-",
    on: "シン, ジン",
    meaning: "Gods, mind, soul",
  },
  {
    kanji: "配",
    kun: "くば. る",
    on: "ハイ",
    meaning: "Distribute, spouse, exile, rationing",
  },
  {
    kanji: "育",
    kun: "そだ. つ, そだ. ち, そだ. てる, はぐく. む",
    on: "イク",
    meaning: "Bring up, grow up, raise, rear",
  },
  {
    kanji: "乗",
    kun: "の. る, -の. り, の. せる",
    on: "ジョウ, ショウ",
    meaning:
      "Ride, power, multiplication, record, counter for vehicles, board, mount, join",
  },
  {
    kanji: "想",
    kun: "おも. う",
    on: "ソウ, ソ",
    meaning: "Concept, think, idea, thought",
  },
  {
    kanji: "農",
    on: "ノウ",
    meaning: "Agriculture, farmers",
  },
  {
    kanji: "州",
    kun: "す",
    on: "シュウ, ス",
    meaning: "State, province",
  },
  {
    kanji: "助",
    kun: "たす. ける, たす. かる, す. ける, すけ",
    on: "ジョ",
    meaning: "Help, rescue, assist",
  },
  {
    kanji: "追",
    kun: "お. う",
    on: "ツイ",
    meaning: "Chase, drive away, follow, pursue, meanwhile",
  },
  {
    kanji: "商",
    kun: "あきな. う",
    on: "ショウ",
    meaning: "Make a deal, selling, dealing in, merchant",
  },
  {
    kanji: "葉",
    kun: "は",
    on: "ヨウ",
    meaning:
      "Leaf, plane, lobe, needle, blade, spear, counter for flat things, fragment, piece",
  },
  {
    kanji: "落",
    kun: "お. ちる, お. ち, お. とす",
    on: "ラク",
    meaning: "Fall, drop, come down",
  },
  {
    kanji: "勉",
    kun: "つと. める",
    on: "ベン",
    meaning: "Exertion",
  },
  {
    kanji: "負",
    kun: "ま. ける, ま. かす, お. う",
    on: "フ",
    meaning: "defeat, negative, minus, bear, owe, assume a responsibility",
  },
  {
    kanji: "守",
    kun: "まも. る, まも. り, もり, -もり, かみ",
    on: "シュ, ス",
    meaning: "Guard, protect, defend, obey",
  },
  {
    kanji: "美",
    kun: "うつく. しい",
    on: "ビ, ミ",
    meaning: "Beauty, beautiful",
  },
  {
    kanji: "命",
    kun: "いのち",
    on: "メイ, ミョウ",
    meaning: "Fate, command, decree, destiny, life, appoint",
  },
  {
    kanji: "福",
    on: "フク",
    meaning: "Blessing, fortune, luck, wealth",
  },
  {
    kanji: "横",
    kun: "よこ",
    on: "オウ",
    meaning: "Sideways, side, horizontal, width, woof",
  },
  {
    kanji: "深",
    kun: "ふか. い, -ぶか. い, ふか. まる, ふか. める, み-",
    on: "シン",
    meaning: "Deep, heighten, intensify, strengthen",
  },
  {
    kanji: "申",
    kun: "もう. す, もう. し-, さる",
    on: "シン",
    meaning:
      "Have the honor to, sign of the monkey, 3-5PM, ninth sign of Chinese zodiac",
  },
  {
    kanji: "様",
    kun: "さま, さん",
    on: "ヨウ, ショウ",
    meaning: "Way, manner, situation, polite suffix",
  },
  {
    kanji: "港",
    kun: "みなと",
    on: "コウ",
    meaning: "Harbor",
  },
  {
    kanji: "階",
    kun: "きざはし",
    on: "カイ",
    meaning: "Storey, stair, counter for storeys of a building",
  },
  {
    kanji: "路",
    kun: "-じ, みち",
    on: "ロ, ル",
    meaning: "Path, route, road, distance",
  },
  {
    kanji: "他",
    kun: "ほか",
    on: "タ",
    meaning: "Other, another, the others",
  },
  {
    kanji: "橋",
    kun: "はし",
    on: "キョウ",
    meaning: "Bridge",
  },
  {
    kanji: "岸",
    kun: "きし",
    on: "ガン",
    meaning: "Beach",
  },
  {
    kanji: "客",
    on: "キャク, カク",
    meaning: "Guest, visitor, customer, client",
  },
  {
    kanji: "登",
    kun: "のぼ. る, あ. がる",
    on: "トウ, ト, ドウ, ショウ, チョウ",
    meaning: "Ascend, climb up",
  },
  {
    kanji: "速",
    kun: "はや. い, はや-, はや. める, すみ. やか",
    on: "ソク",
    meaning: "Quick, fast",
  },
  {
    kanji: "央",
    on: "オウ",
    meaning: "Center, middle",
  },
  {
    kanji: "号",
    kun: "さけ. ぶ, よびな",
    on: "ゴウ",
    meaning: "Nickname, number, item, title, pseudonym, name, call",
  },
  {
    kanji: "根",
    kun: "ね, -ね",
    on: "コン",
    meaning: "Root, radical, root (of a tooth, hair, etc.)",
  },
  {
    kanji: "苦",
    kun: "くる. しい, -ぐる. しい, くる. しむ, くる. しめる",
    on: "ク",
    meaning: "Suffering, trial, worry, hardship, feel bitter, scowl",
  },
  {
    kanji: "具",
    kun: "そな. える, つぶさ. に",
    on: "グ",
    meaning:
      "Tool, utensil, means, possess, ingredients, counter for armor, suits, sets of furniture",
  },
  {
    kanji: "鉄",
    kun: "くろがね",
    on: "テツ",
    meaning: "Iron",
  },
  {
    kanji: "返",
    kun: "かえ. す, -かえ. す, かえ. る, -かえ. る",
    on: "ヘン",
    meaning: "Return, answer, fade, repay",
  },
  {
    kanji: "短",
    kun: "みじか. い",
    on: "タン",
    meaning: "Short, brevity, fault, defect, weak point",
  },
  {
    kanji: "油",
    kun: "あぶら",
    on: "ユ, ユウ",
    meaning: "Oil, fat",
  },
  {
    kanji: "植",
    kun: "う. える, う. わる",
    on: "ショク",
    meaning: "Plant",
  },
  {
    kanji: "宿",
    kun: "やど, やど. る, やど. す",
    on: "シュク",
    meaning:
      "Inn, lodging, relay station, dwell, lodge, be pregnant, home, dwelling",
  },
  {
    kanji: "薬",
    kun: "くすり",
    on: "ヤク",
    meaning: "Medicine, chemical, enamel, gunpowder, benefit",
  },
  {
    kanji: "倍",
    on: "バイ",
    meaning: "Double, twice, times, fold",
  },
  {
    kanji: "波",
    kun: "なみ",
    on: "ハ",
    meaning: "Waves, billows, Poland",
  },
  {
    kanji: "第",
    on: "ダイ, テイ",
    meaning: "Prefix for forming ordinal numbers",
  },
  {
    kanji: "幸",
    kun: "さいわ. い, さち, しあわ. せ",
    on: "コウ",
    meaning: "Happiness, blessing, fortune",
  },
  {
    kanji: "練",
    kun: "ね. る, ね. り",
    on: "レン",
    meaning: "Practice, gloss, train, drill, polish, refine",
  },
  {
    kanji: "軽",
    kun: "かる. い, かろ. やか, かろ. んじる",
    on: "ケイ",
    meaning: "Lightly, trifling, unimportant",
  },
  {
    kanji: "等",
    kun: "ひと. しい, など, -ら",
    on: "トウ",
    meaning: "Etc., and so forth, class (first), quality, equal, similar",
  },
  {
    kanji: "曲",
    kun: "ま. がる, ま. げる, くま",
    on: "キョク",
    meaning:
      "Bend, music, melody, composition, pleasure, injustice, fault, curve, crooked, perverse, lean",
  },
  {
    kanji: "庭",
    kun: "にわ",
    on: "テイ",
    meaning: "Courtyard, garden, yard",
  },
  {
    kanji: "血",
    kun: "ち",
    on: "ケツ",
    meaning: "Blood",
  },
  {
    kanji: "温",
    kun: "あたた. か, あたた. かい, あたた. まる, あたた. める",
    on: "オン",
    meaning: "Warm",
  },
  {
    kanji: "庫",
    kun: "くら",
    on: "コ, ク",
    meaning: "Warehouse, storehouse",
  },
  {
    kanji: "漢",
    on: "カン",
    meaning: "China",
  },
  {
    kanji: "坂",
    kun: "さか",
    on: "ハン",
    meaning: "Slope, incline, hill",
  },
  {
    kanji: "息",
    kun: "いき",
    on: "ソク",
    meaning: "Breath, respiration, son, interest (on money)",
  },
  {
    kanji: "板",
    kun: "いた",
    on: "ハン, バン",
    meaning: "Plank, board, plate, stage",
  },
  {
    kanji: "列",
    on: "レツ, レ",
    meaning: "File, row, rank, tier, column",
  },
  {
    kanji: "遊",
    kun: "あそ. ぶ, あそ. ばす",
    on: "ユウ, ユ",
    meaning: "Play",
  },
  {
    kanji: "君",
    kun: "きみ, -ぎみ",
    on: "クン",
    meaning: "Old boy, name suffix, you, buddy, pal",
  },
  {
    kanji: "章",
    on: "ショウ",
    meaning: "Badge, chapter, composition, poem, design",
  },
  {
    kanji: "宮",
    kun: "みや",
    on: "キュウ, グウ, ク, クウ",
    meaning: "Shinto shrine, constellations, palace, princess",
  },
  {
    kanji: "酒",
    kun: "さけ, さか-",
    on: "シュ",
    meaning: "Sake, alcohol",
  },
  {
    kanji: "悲",
    kun: "かな. しい, かな. しむ",
    on: "ヒ",
    meaning: "Jail cell, grieve, sad, deplore, regret",
  },
  {
    kanji: "秒",
    on: "ビョウ",
    meaning: "Second (1/60 minute)",
  },
  {
    kanji: "暗",
    kun: "くら. いくら. む, くれ. る",
    on: "アン",
    meaning: "Darkness, disappear, shade, informal, grow dark, be blinded",
  },
  {
    kanji: "陽",
    kun: "ひ",
    on: "ヨウ",
    meaning: "Sunshine, yang principle, positive, male, heaven, daytime",
  },
  {
    kanji: "皮",
    kun: "かわ",
    on: "ヒ",
    meaning: "Pelt, skin, hide, leather",
  },
  {
    kanji: "整",
    kun: "ととの. える, ととの. う",
    on: "セイ",
    meaning: "Organize, arranging, tune, tone, meter, key (music)",
  },
  {
    kanji: "歯",
    kun: "よわい, は, よわ. い, よわい. する",
    on: "シ",
    meaning: "Tooth, cog",
  },
  {
    kanji: "柱",
    kun: "はしら",
    on: "チュウ",
    meaning: "Pillar, post, cylinder, support",
  },
  {
    kanji: "祭",
    kun: "まつ. る, まつ. り, まつり",
    on: "サイ",
    meaning: "Ritual, offer prayers, celebrate, deify, enshrine, worship",
  },
  {
    kanji: "筆",
    kun: "ふで",
    on: "ヒツ",
    meaning: "Writing brush, writing, painting brush, handwriting",
  },
  {
    kanji: "童",
    kun: "わらべ",
    on: "ドウ",
    meaning: "Juvenile, child",
  },
  {
    kanji: "畑",
    kun: "はた, はたけ, -ばたけ",
    meaning: "Farm, field, garden, one’s specialty, (kokuji)",
  },
  {
    kanji: "緑",
    kun: "みどり",
    on: "リョク, ロク",
    meaning: "Green",
  },
  {
    kanji: "礼",
    on: "レイ, ライ",
    meaning: "Salute, bow, ceremony, thanks, remuneration",
  },
  {
    kanji: "昔",
    kun: "むかし",
    on: "セキ, シャク",
    meaning: "Once upon a time, antiquity, old times",
  },
  {
    kanji: "泳",
    kun: "およ. ぐ",
    on: "エイ",
    meaning: "Swim",
  },
  {
    kanji: "荷",
    kun: "に",
    on: "カ",
    meaning:
      "Baggage, shoulder?pole load, bear (a burden), shoulder (a gun), load, cargo, freight",
  },
  {
    kanji: "炭",
    kun: "すみ",
    on: "タン",
    meaning: "Charcoal, coal",
  },
  {
    kanji: "昭",
    on: "ショウ",
    meaning: "Shining, bright",
  },
  {
    kanji: "湖",
    kun: "みずうみ",
    on: "コ",
    meaning: "Lake",
  },
  {
    kanji: "湯",
    kun: "ゆ",
    on: "トウ",
    meaning: "Hot water, bath, hot spring",
  },
  {
    kanji: "箱",
    kun: "はこ",
    on: "ソウ",
    meaning: "Box, chest, case, bin, railway car",
  },
  {
    kanji: "級",
    on: "キュウ",
    meaning: "Class, rank, grade",
  },
  {
    kanji: "氷",
    kun: "こおり, ひ, こお. る",
    on: "ヒョウ",
    meaning: "Icicle, ice, hail, freeze, congeal",
  },
  {
    kanji: "寒",
    kun: "さむ. い",
    on: "カン",
    meaning: "Cold",
  },
  {
    kanji: "拾",
    kun: "ひろ. う",
    on: "シュウ, ジュウ",
    meaning: "Pick up, gather, find, go on foot, ten",
  },
  {
    kanji: "鼻",
    kun: "はな",
    on: "ビ",
    meaning: "Nose, snout",
  },
  {
    kanji: "皿",
    kun: "さら",
    on: "ベイ",
    meaning: "Dish, a helping, plate",
  },
  {
    kanji: "詩",
    kun: "うた",
    on: "シ",
    meaning: "Poem, poetry",
  },
  {
    kanji: "丁",
    kun: "ひのと",
    on: "チョウ, テイ, チン, トウ, チ",
    meaning:
      "Street, ward, town, counter for guns, tools, leaves or cakes of someth, even number, 4th calendar sign",
  },
  {
    kanji: "豆",
    kun: "まめ, まめ-",
    on: "トウ, ズ",
    meaning: "beans, pea, midget",
  },
  {
    kanji: "暑",
    kun: "あつ. い",
    on: "ショ",
    meaning: "Sultry, hot, summer heat",
  },
  {
    kanji: "帳",
    kun: "とばり",
    on: "チョウ",
    meaning: "Notebook, account book, album",
  },
  {
    kanji: "羊",
    kun: "ひつじ",
    on: "ヨウ",
    meaning: "Sheep",
  },
  {
    kanji: "笛",
    kun: "ふえ",
    on: "テキ",
    meaning: "Flute, clarinet, pipe, whistle, bagpipe, piccolo",
  },
];

export default Grade3;
