const Grade2 = [
  {
    kanji: "国",
    kun: "くに",
    on: "コク",
    meaning: "Country",
  },
  {
    kanji: "長",
    kun: "なが. い, おさ",
    on: "チョウ",
    meaning: "Long, leader",
  },
  {
    kanji: "時",
    kun: "とき, -どき",
    on: "ジ",
    meaning: "Time, hour",
  },
  {
    kanji: "行",
    kun: "い. く, ゆ. く, -ゆ. き, -ゆき, -い. き, -いき",
    on: "コウ, ギョウ, アン",
    meaning: "Going, journey",
  },
  {
    kanji: "分",
    kun: "わ. ける, わ. け, わ. かれる, わ. かる, わ. かつ",
    on: "ブン, フン, ブ",
    meaning:
      "Part, minute of time, segment, share, degree, one’s lot, duty, understand, know, rate, 1%, chances",
  },
  {
    kanji: "後",
    kun: "のち, うし. ろ, うしろ, あと, おく. れる",
    on: "ゴ, コウ",
    meaning: "Behind, back, later",
  },
  {
    kanji: "前",
    kun: "まえ, -まえ",
    on: "ゼン",
    meaning: "In front, before",
  },
  {
    kanji: "間",
    kun: "あいだ, ま, あい",
    on: "カン, ケン",
    meaning: "Interval, space",
  },
  {
    kanji: "東",
    kun: "ひがし",
    on: "トウ",
    meaning: "East",
  },
  {
    kanji: "今",
    kun: "いま",
    on: "コン, キン",
    meaning: "Now",
  },
  {
    kanji: "高",
    kun: "たか. い, たか, -だか, たか. まる, たか. める",
    on: "コウ",
    meaning: "Tall, high, expensive",
  },
  {
    kanji: "外",
    kun: "そと, ほか, はず. す, はず. れる, と-",
    on: "ガイ, ゲ",
    meaning: "Outside",
  },
  {
    kanji: "来",
    kun: "く. る, きた. る, きた. す, き. たす, き. たる, き",
    on: "ライ, タイ",
    meaning: "Come, due, next, cause, become",
  },
  {
    kanji: "話",
    kun: "はな. す, はなし",
    on: "ワ",
    meaning: "Tale, talk",
  },
  {
    kanji: "北",
    kun: "きた",
    on: "ホク",
    meaning: "North",
  },
  {
    kanji: "午",
    kun: "うま",
    on: "ゴ",
    meaning:
      "Noon, sign of the horse, 11AM to 1PM, seventh sign of Chinese zodiac",
  },
  {
    kanji: "書",
    kun: "か. く, -が. き, -がき",
    on: "ショ",
    meaning: "Write",
  },
  {
    kanji: "半",
    kun: "なか. ば",
    on: "ハン",
    meaning: "Half, middle, odd number, semi, part",
  },
  {
    kanji: "西",
    kun: "にし",
    on: "セイ, サイ, ス",
    meaning: "West, Spain",
  },
  {
    kanji: "電",
    on: "デン",
    meaning: "Electricity",
  },
  {
    kanji: "語",
    kun: "かた. る, かた. らう",
    on: "ゴ",
    meaning: "Word, speech, language",
  },
  {
    kanji: "聞",
    kun: "き. く, き. こえる",
    on: "ブン, モン",
    meaning: "Hear, ask, listen",
  },
  {
    kanji: "食",
    kun: "く. う, く. らう, た. べる, は. む",
    on: "ショク, ジキ",
    meaning: "Eat, food",
  },
  {
    kanji: "何",
    kun: "なに, なん, なに-, なん-",
    on: "カ",
    meaning: "What",
  },
  {
    kanji: "南",
    kun: "みなみ",
    on: "ナン, ナ",
    meaning: "South",
  },
  {
    kanji: "万",
    kun: "よろず",
    on: "マン, バン",
    meaning: "Ten thousand, 10.000",
  },
  {
    kanji: "毎",
    kun: "ごと, -ごと. に",
    on: "マイ",
    meaning: "Every",
  },
  {
    kanji: "母",
    kun: "はは, も",
    on: "ボ",
    meaning: "Mom, mother",
  },
  {
    kanji: "読",
    kun: "よ. む, -よ. み",
    on: "ドク, トク, トウ",
    meaning: "Read",
  },
  {
    kanji: "友",
    kun: "とも",
    on: "ユウ",
    meaning: "Friend",
  },
  {
    kanji: "会",
    kun: "あ. う, あ. わせる, あつ. まる",
    on: "カイ, エ",
    meaning: "Meeting, meet, party, association, interview, join",
  },
  {
    kanji: "同",
    kun: "おな. じ",
    on: "ドウ",
    meaning: "Same, agree, equal",
  },
  {
    kanji: "自",
    kun: "みずか. ら, おの. ずから, おの. ずと",
    on: "ジ, シ",
    meaning: "Oneself",
  },
  {
    kanji: "社",
    kun: "やしろ",
    on: "シャ",
    meaning: "Company, firm, office, association, shrine",
  },
  {
    kanji: "父",
    kun: "ちち",
    on: "フ",
    meaning: "Father",
  },
  {
    kanji: "地",
    on: "チ, ジ",
    meaning: "Ground, earth",
  },
  {
    kanji: "方",
    kun: "かた, -かた, -がた",
    on: "ホウ",
    meaning: "Direction, person, alternative",
  },
  {
    kanji: "新",
    kun: "あたら. しい, あら. た, あら-, にい-",
    on: "シン",
    meaning: "New",
  },
  {
    kanji: "場",
    kun: "ば",
    on: "ジョウ, チョウ",
    meaning: "Location, place",
  },
  {
    kanji: "明",
    kun: "あ. かり, あか. るい, あか. るむ, あか. らむ",
    on: "メイ, ミョウ, ミン",
    meaning: "Bright, light",
  },
  {
    kanji: "京",
    kun: "みやこ",
    on: "キョウ, ケイ, キン",
    meaning: "Capital",
  },
  {
    kanji: "通",
    kun: "とお. る, とお. り, -とお. り, -どお. り, とお. す",
    on: "ツウ, ツ",
    meaning:
      "Traffic, pass through, avenue, commute, counter for letters, notes, documents, etc.",
  },
  {
    kanji: "言",
    kun: "い. う, こと",
    on: "ゲン, ゴン",
    meaning: "Say",
  },
  {
    kanji: "理",
    kun: "ことわり",
    on: "リ",
    meaning: "Logic, arrangement, reason, justice, truth",
  },
  {
    kanji: "体",
    kun: "からだ, かたち",
    on: "タイ, テイ",
    meaning: "Body, substance, object, reality, counter for images",
  },
  {
    kanji: "作",
    kun: "つく. る, つく. り, -づく. り",
    on: "サク, サ",
    meaning: "Make, production, prepare, build",
  },
  {
    kanji: "用",
    kun: "もち. いる",
    on: "ヨウ",
    meaning: "Utilize, business, service, use, employ",
  },
  {
    kanji: "強",
    kun: "つよ. い, つよ. まる, つよ. める, し. いる, こわ. い",
    on: "キョウ, ゴウ",
    meaning: "Strong",
  },
  {
    kanji: "公",
    kun: "おおやけ",
    on: "コウ, ク",
    meaning: "Public, prince, official, governmental",
  },
  {
    kanji: "野",
    kun: "の, の-",
    on: "ヤ, ショ",
    meaning: "Plains, field, rustic, civilian life",
  },
  {
    kanji: "思",
    kun: "おも. う, おもえら. く, おぼ. す",
    on: "シ",
    meaning: "Think",
  },
  {
    kanji: "家",
    kun: "いえ, や, うち",
    on: "カ, ケ",
    meaning: "House, home",
  },
  {
    kanji: "多",
    kun: "おお. い, まさ. に, まさ. る",
    on: "タ",
    meaning: "Many, frequent, much",
  },
  {
    kanji: "心",
    kun: "こころ, -ごころ",
    on: "シン",
    meaning: "Heart, mind, spirit",
  },
  {
    kanji: "教",
    kun: "おし. える, おそ. わる",
    on: "キョウ",
    meaning: "Teach, faith, doctrine",
  },
  {
    kanji: "元",
    kun: "もと",
    on: "ゲン, ガン",
    meaning: "Beginning, former time, origin",
  },
  {
    kanji: "近",
    kun: "ちか. い",
    on: "キン, コン",
    meaning: "Near, early, akin, tantamount",
  },
  {
    kanji: "考",
    kun: "かんが. える, かんが. え",
    on: "コウ",
    meaning: "Consider, think over",
  },
  {
    kanji: "画",
    kun: "えが. く, かく. する, かぎ. る, はかりごと, はか. る",
    on: "ガ, カク, エ, カイ",
    meaning: "Brush stroke, picture",
  },
  {
    kanji: "海",
    kun: "うみ",
    on: "カイ",
    meaning: "Sea, ocean",
  },
  {
    kanji: "売",
    kun: "う. る, う. れる",
    on: "バイ",
    meaning: "Sell",
  },
  {
    kanji: "知",
    kun: "し. る, し. らせる",
    on: "チ",
    meaning: "Know, wisdom",
  },
  {
    kanji: "道",
    kun: "みち",
    on: "ドウ, トウ",
    meaning: "Roadway, street, district, journey, course, moral, teachings",
  },
  {
    kanji: "計",
    kun: "はか. る, はか. らう",
    on: "ケイ",
    meaning: "Plot, plan, scheme, measure",
  },
  {
    kanji: "朝",
    kun: "あさ",
    on: "チョウ",
    meaning: "Morning, dynasty, regime, epoch, period, (North) Korea",
  },
  {
    kanji: "台",
    kun: "うてな, われ, つかさ",
    on: "ダイ, タイ",
    meaning: "Pedestal, a stand, counter for machines and vehicles",
  },
  {
    kanji: "広",
    kun: "ひろ. い, ひろ. まる, ひろ. める, ひろ. がる",
    on: "コウ",
    meaning: "Wide, broad, spacious",
  },
  {
    kanji: "少",
    kun: "すく. ない, すこ. し",
    on: "ショウ",
    meaning: "Few, little",
  },
  {
    kanji: "工",
    on: "コウ, ク, グ",
    meaning: "Craft, construction, on e",
  },
  {
    kanji: "止",
    kun: "と. まる, -ど. まり, と. める, -と. める, -ど. め",
    on: "シ",
    meaning: "Stop, halt",
  },
  {
    kanji: "切",
    kun: "き. る, -き. る, き. り, -き. り, -ぎ. り",
    on: "セツ, サイ",
    meaning: "Cut, cutoff, be sharp",
  },
  {
    kanji: "楽",
    kun: "たの. しい, たの. しむ, この. むガク, ラク, ゴウ",
    on: "ガク, ラク, ゴウ",
    meaning: "Music, comfort, ease",
  },
  {
    kanji: "店",
    kun: "みせ, たな",
    on: "テン",
    meaning: "Store, shop",
  },
  {
    kanji: "親",
    kun: "おや, おや-, した. しい, した. しむ",
    on: "シン",
    meaning: "Parent, intimacy, relative, familiarity, dealer (cards)",
  },
  {
    kanji: "答",
    kun: "こた. える, こた. え",
    on: "トウ",
    meaning: "Solution, answer",
  },
  {
    kanji: "夜",
    kun: "よ, よる",
    on: "ヤ",
    meaning: "Night, evening",
  },
  {
    kanji: "帰",
    kun: "かえ. る, かえ. す, おく. る, とつ. ぐ",
    on: "キ",
    meaning: "Homecoming, arrive at, lead to, result in",
  },
  {
    kanji: "古",
    kun: "ふる. い, ふる-, -ふる. す",
    on: "コ",
    meaning: "Old",
  },
  {
    kanji: "歌",
    kun: "うた, うた. う",
    on: "カ",
    meaning: "Song, sing",
  },
  {
    kanji: "買",
    kun: "か. う",
    on: "バイ",
    meaning: "Buy",
  },
  {
    kanji: "図",
    kun: "え, はか. る",
    on: "ズ, ト",
    meaning: "Map, drawing, plan, unexpected, accidentally",
  },
  {
    kanji: "週",
    on: "シュウ",
    meaning: "Week",
  },
  {
    kanji: "室",
    kun: "むろ",
    on: "シツ",
    meaning: "Room, apartment, chamber, greenhouse, cellar",
  },
  {
    kanji: "歩",
    kun: "ある. く, あゆ. む",
    on: "ホ, ブ, フ",
    meaning: "Walk, counter for steps",
  },
  {
    kanji: "風",
    kun: "かぜ, かざ-, -かぜ",
    on: "フウ, フ",
    meaning: "Wind, air, style, manner",
  },
  {
    kanji: "紙",
    kun: "かみ",
    on: "シ",
    meaning: "Paper",
  },
  {
    kanji: "黒",
    kun: "くろ, くろ. ずむ, くろ. い",
    on: "コク",
    meaning: "Black",
  },
  {
    kanji: "春",
    kun: "はる",
    on: "シュン",
    meaning: "Springtime, spring (season)",
  },
  {
    kanji: "色",
    kun: "いろ",
    on: "ショク, シキ",
    meaning: "Color",
  },
  {
    kanji: "走",
    kun: "はし. る",
    on: "ソウ",
    meaning: "Run",
  },
  {
    kanji: "秋",
    kun: "あき, とき",
    on: "シュウ",
    meaning: "Autumn",
  },
  {
    kanji: "夏",
    kun: "なつ",
    on: "カ, ガ, ゲ",
    meaning: "Summer",
  },
  {
    kanji: "合",
    kun: "あ. う, -あ. う, あ. い, あい-, -あ. い, -あい",
    on: "ゴウ, ガッ, カッ",
    meaning: "Fit, suit, join, 0.1",
  },
  {
    kanji: "市",
    kun: "いち",
    on: "シ",
    meaning: "Market, city, town",
  },
  {
    kanji: "内",
    kun: "うち",
    on: "ナイ, ダイ",
    meaning: "Inside, within, between, among, house, home",
  },
  {
    kanji: "回",
    kun: "まわ. る, -まわ. る, -まわ. り, まわ. す",
    on: "カイ, エ",
    meaning: "Times, round, game, revolve, counter for occurrences",
  },
  {
    kanji: "米",
    kun: "こめ, よね",
    on: "ベイ, マイ, メエトル",
    meaning: "Rice, USA, metre",
  },
  {
    kanji: "当",
    kun: "あ. たる, あ. たり, あ. てる, あ. て, まさ. に",
    on: "トウ",
    meaning: "Hit, right, appropriate, himself",
  },
  {
    kanji: "首",
    kun: "くび",
    on: "シュ",
    meaning: "Neck, counter for songs and poems",
  },
  {
    kanji: "数",
    kun: "かず, かぞ. える, しばしば, せ. める, わず らわ. しい",
    on: "スウ, ス, サク, ソク, シュ",
    meaning: "Number, strength, fate, law, figures",
  },
  {
    kanji: "記",
    kun: "しる. す",
    on: "キ",
    meaning: "Scribe, account, narrative",
  },
  {
    kanji: "点",
    kun: "つ. ける, つ. く, た. てる, さ. す, とぼ. す",
    on: "テン",
    meaning: "Spot, point, mark, speck, decimal point",
  },
  {
    kanji: "活",
    kun: "い. きる, い. かす, い. ける",
    on: "カツ",
    meaning: "Lively, resuscitation, being helped, living",
  },
  {
    kanji: "原",
    kun: "はら",
    on: "ゲン",
    meaning:
      "Meadow, original, primitive, field, plain, prairie, tundra, wilderness",
  },
  {
    kanji: "交",
    kun: "まじ. わる, まじ. える, ま. じる, まじ. る, ま. ざる",
    on: "コウ",
    meaning: "Mingle, mixing, association, coming & going",
  },
  {
    kanji: "組",
    kun: "く. む, くみ, -ぐみ",
    on: "ソ",
    meaning:
      "Association, braid, plait, construct, assemble, unite, cooperate, grapple",
  },
  {
    kanji: "引",
    kun: "ひ. く, ひ. き, ひ. き-, -び. き, ひ. ける",
    on: "イン",
    meaning: "Pull, tug, jerk, admit, install, quote, refer to",
  },
  {
    kanji: "直",
    kun: "ただ. ちに, なお. す, -なお. す, なお. る, なお. き",
    on: "チョク, ジキ, ジカ",
    meaning: "Straightaway, honesty, frankness, fix, repair",
  },
  {
    kanji: "曜",
    on: "ヨウ",
    meaning: "Weekday",
  },
  {
    kanji: "番",
    kun: "つが. い",
    on: "バン",
    meaning: "Turn, number in a series",
  },
  {
    kanji: "算",
    kun: "そろ",
    on: "サン",
    meaning: "Calculate, divining, number, abacus, probability",
  },
  {
    kanji: "肉",
    kun: "しし",
    on: "ニク",
    meaning: "Meat",
  },
  {
    kanji: "線",
    kun: "すじ",
    on: "セン",
    meaning: "Line, track",
  },
  {
    kanji: "声",
    kun: "こえ, こわ-",
    on: "セイ, ショウ",
    meaning: "Voice",
  },
  {
    kanji: "形",
    kun: "かた, -がた, かたち, なり",
    on: "ケイ, ギョウ",
    meaning: "Shape, form, style",
  },
  {
    kanji: "鳥",
    kun: "とり",
    on: "チョウ",
    meaning: "Bird, chicken",
  },
  {
    kanji: "頭",
    kun: "あたま, かしら, -がしら, かぶり",
    on: "トウ, ズ, ト",
    meaning: "Head, counter for large animals",
  },
  {
    kanji: "門",
    kun: "かど, と",
    on: "モン",
    meaning: "Gate, counter for cannons",
  },
  {
    kanji: "冬",
    kun: "ふゆ",
    on: "トウ",
    meaning: "Winter",
  },
  {
    kanji: "昼",
    kun: "ひる",
    on: "チュウ",
    meaning: "Daytime, noon",
  },
  {
    kanji: "茶",
    on: "チャ, サ",
    meaning: "Tea",
  },
  {
    kanji: "谷",
    kun: "たに, きわ. まる",
    on: "コク",
    meaning: "Valley",
  },
  {
    kanji: "光",
    kun: "ひか. る, ひかり",
    on: "コウ",
    meaning: "Ray, light",
  },
  {
    kanji: "科",
    on: "カ",
    meaning: "Department, course, section",
  },
  {
    kanji: "弟",
    kun: "おとうと",
    on: "テイ, ダイ, デ",
    meaning: "Younger brother, faithful service to elders",
  },
  {
    kanji: "細",
    kun: "ほそ. い, ほそ. る, こま. か, こま. かい",
    on: "サイ",
    meaning: "Dainty, get thin, taper, slender, narrow",
  },
  {
    kanji: "丸",
    kun: "まる, まる. める, まる. い",
    on: "ガン",
    meaning:
      "round, full, month, perfection, pills, make round, roll up, curl up, seduce, explain away",
  },
  {
    kanji: "太",
    kun: "ふと. い, ふと. る",
    on: "タイ, タ",
    meaning: "Plump, thick, big around",
  },
  {
    kanji: "戸",
    kun: "と",
    on: "コ",
    meaning: "door, counter for houses",
  },
  {
    kanji: "牛",
    kun: "うし",
    on: "ギュウ",
    meaning: "Cow",
  },
  {
    kanji: "魚",
    kun: "うお, さかな, -ざかな",
    on: "ギョ",
    meaning: "Fish",
  },
  {
    kanji: "兄",
    kun: "あに",
    on: "ケイ, キョウ",
    meaning: "Elder brother, big brother",
  },
  {
    kanji: "園",
    kun: "その",
    on: "エン",
    meaning: "Park, garden, yard, farm",
  },
  {
    kanji: "馬",
    kun: "うま, うま-, ま",
    on: "バ",
    meaning: "Horse",
  },
  {
    kanji: "顔",
    kun: "かお",
    on: "ガン",
    meaning: "Face, expression",
  },
  {
    kanji: "船",
    kun: "ふね, ふな-",
    on: "セン",
    meaning: "Ship, boat",
  },
  {
    kanji: "羽",
    kun: "は, わ, はね",
    on: "ウ",
    meaning: "Feathers, counter for birds, rabbits",
  },
  {
    kanji: "岩",
    kun: "いわ",
    on: "ガン",
    meaning: "Boulder, rock, clif",
  },
  {
    kanji: "角",
    kun: "かど, つの",
    on: "カク",
    meaning: "Angle, corner, square, horn, antlers",
  },
  {
    kanji: "妹",
    kun: "いもうと",
    on: "マイ",
    meaning: "Younger sister",
  },
  {
    kanji: "池",
    kun: "いけ",
    on: "チ",
    meaning: "Pond, cistern, pool, reservoir",
  },
  {
    kanji: "星",
    kun: "ほし, -ぼし",
    on: "セイ, ショウ",
    meaning: "Star, spot, dot, mark",
  },
  {
    kanji: "姉",
    kun: "あね, はは",
    on: "シ",
    meaning: "Elder sister",
  },
  {
    kanji: "寺",
    kun: "てら",
    on: "ジ",
    meaning: "Buddhist temple",
  },
  {
    kanji: "遠",
    kun: "とお. い",
    on: "エン, オン",
    meaning: "Distant, far",
  },
  {
    kanji: "絵",
    on: "カイ, エ",
    meaning: "Picture, drawing, painting, sketch",
  },
  {
    kanji: "弱",
    kun: "よわ. い, よわ. る, よわ. まる, よわ. める",
    on: "ジャク",
    meaning: "Weak, frail",
  },
  {
    kanji: "晴",
    kun: "は. れる, は. れ, は. れ-, -ば. れ, は. らす",
    on: "セイ",
    meaning: "Clear up",
  },
  {
    kanji: "雪",
    kun: "ゆき",
    on: "セツ",
    meaning: "Snow",
  },
  {
    kanji: "毛",
    kun: "け",
    on: "モウ",
    meaning: "Fur, hair, feather, down",
  },
  {
    kanji: "黄",
    kun: "き, こ-",
    on: "コウ, オウ",
    meaning: "Yellow",
  },
  {
    kanji: "雲",
    kun: "くも, -ぐも",
    on: "ウン",
    meaning: "Cloud",
  },
  {
    kanji: "鳴",
    kun: "な. く, な. る, な. らす",
    on: "メイ",
    meaning: "Chirp, cry, bark, sound, ring, echo, honk",
  },
  {
    kanji: "才",
    on: "サイ",
    meaning: "Genius, years old, cubic shaku",
  },
  {
    kanji: "麦",
    kun: "むぎ",
    on: "バク",
    meaning: "Barley, wheat",
  },
  {
    kanji: "里",
    kun: "さと",
    on: "リ",
    meaning:
      "Ri (old Japanese unit of distance), village, parent’s home, league",
  },
  {
    kanji: "矢",
    kun: "や",
    on: "シ",
    meaning: "Dart, arrow",
  },
  {
    kanji: "刀",
    kun: "かたな, そり",
    on: "トウ",
    meaning: "Sword, saber, knife",
  },
  {
    kanji: "弓",
    kun: "ゆみ",
    on: "キュウ",
    meaning: "Bow, bow (archery, violin)",
  },
  {
    kanji: "汽",
    on: "キ",
    meaning: "Vapor, steam",
  },
];

export default Grade2;
