const Grade1 = [
  {
    kanji: "日",
    kun: "ひ, -び, -か",
    on: "ニチ, ジツ",
    meaning: "day, sun, Japan, counter for days",
  },
  {
    kanji: "一",
    kun: "ひと-, ひと. つ",
    on: "イチ, イツ",
    meaning: "One",
  },
  {
    kanji: "人",
    kun: "ひと, -り, つ",
    on: "ジン, ニン",
    meaning: "Person",
  },
  {
    kanji: "年",
    kun: "とし",
    on: "ネン",
    meaning: "Year, counter for years",
  },
  {
    kanji: "大",
    kun: "おお-, おお. きい, -おお. いに",
    on: "ダイ, タイ",
    meaning: "Large, big",
  },
  {
    kanji: "十",
    kun: "とお, と",
    on: "ジュウ, ジッ, ジュッ",
    meaning: "Ten",
  },
  {
    kanji: "二",
    kun: "ふた, ふた. つ, ふたた. び",
    on: "ニ, ジ",
    meaning: "Two",
  },
  {
    kanji: "本",
    kun: "もと",
    on: "ホン",
    meaning:
      "book, present, main, true, real, counter for long cylindrical things",
  },
  {
    kanji: "中",
    kun: "なか, うち, あた. る",
    on: "チュウ",
    meaning: "in, inside, middle, mean, center",
  },
  {
    kanji: "出",
    kun: "で. る, -で, だ. す, -だ. す, い. でる, い. だす",
    on: "シュツ, スイ",
    meaning: "Exit, leave",
  },
  {
    kanji: "三",
    kun: "み, み. つ, みっ. つ",
    on: "サン, ゾウ",
    meaning: "Three",
  },
  {
    kanji: "見",
    kun: "み. る, み. える, み. せる",
    on: "ケン",
    meaning: "See, hopes, chances, idea, opinion, look at, visible",
  },
  {
    kanji: "月",
    kun: "つき",
    on: "ゲツ, ガツ",
    meaning: "Month, moon",
  },
  {
    kanji: "生",
    kun: "い. きる, い. かす, い. ける, う. まれる, う. まれ",
    on: "セイ, ショウ",
    meaning: "Life, genuine, birth",
  },
  {
    kanji: "五",
    kun: "いつ, いつ. つ",
    on: "ゴ",
    meaning: "Five",
  },
  {
    kanji: "上",
    kun: "うえ, -うえ, うわ-, かみ, あ. げる, -あ. げる",
    on: "ジョウ, ショウ, シャン",
    meaning: "Above, up",
  },
  {
    kanji: "四",
    kun: "よ, よ. つ, よっ. つ, よん",
    on: "シ",
    meaning: "Four",
  },
  {
    kanji: "金",
    kun: "かね, かな-, -がね",
    on: "キン, コン, ゴン",
    meaning: "Gold",
  },
  {
    kanji: "九",
    kun: "ここの, ここの. つ",
    on: "キュウ, ク",
    meaning: "Nine",
  },
  {
    kanji: "入",
    kun: "い. る, -い. る, -い. り, い. れる, -い. れ",
    on: "ニュウ, ジュ",
    meaning: "Enter, insert",
  },
  {
    kanji: "学",
    kun: "まな. ぶ",
    on: "ガク",
    meaning: "Study, learning, science",
  },
  {
    kanji: "円",
    kun: "まる. い, まる, まど, まど. か, まろ. やか",
    on: "エン",
    meaning: "Circle, yen, round",
  },
  {
    kanji: "子",
    kun: "こ, -こ, ね",
    on: "シ, ス, ツ",
    meaning: "Child, 11PM to 1AM, first sign of Chinese zodiac (Rat)",
  },
  {
    kanji: "八",
    kun: "や, や. つ, やっ. つ, よう",
    on: "ハチ",
    meaning: "Eight",
  },
  {
    kanji: "六",
    kun: "む, む. つ, むっ. つ, むい",
    on: "ロク, リク",
    meaning: "Six",
  },
  {
    kanji: "下",
    kun: "した, しも, もと, さ. げる, さ. がる, くだ. る",
    on: "カ, ゲ",
    meaning: "Below, down, descend, give, low, inferior",
  },
  {
    kanji: "気",
    kun: "いき",
    on: "キ, ケ",
    meaning: "Spirit, mind, air, atmosphere, mood",
  },
  {
    kanji: "小",
    kun: "ちい. さい, こ-, お-, さ-",
    on: "ショウ",
    meaning: "Little, small",
  },
  {
    kanji: "七",
    kun: "なな, なな. つ, なの",
    on: "シチ",
    meaning: "Seven",
  },
  {
    kanji: "山",
    kun: "やま",
    on: "サン, セン",
    meaning: "Mountain",
  },
  {
    kanji: "女",
    kun: "おんな, め",
    on: "ジョ, ニョ, ニョウ",
    meaning: "Woman, female",
  },
  {
    kanji: "百",
    kun: "もも",
    on: "ヒャク, ビャク",
    meaning: "Hundred",
  },
  {
    kanji: "先",
    kun: "さき, ま. ず",
    on: "セン",
    meaning: "Before, ahead, previous, future, precedence",
  },
  {
    kanji: "名",
    kun: "な, -な",
    on: "メイ, ミョウ",
    meaning: "Name, noted, distinguished, reputation",
  },
  {
    kanji: "川",
    kun: "かわ",
    on: "セン",
    meaning: "stream, river",
  },
  {
    kanji: "千",
    kun: "ち",
    on: "セン",
    meaning: "Thousand",
  },
  {
    kanji: "水",
    kun: "みず, みず-",
    on: "スイ",
    meaning: "Water",
  },
  {
    kanji: "男",
    kun: "おとこ, お",
    on: "ダン, ナン",
    meaning: "Male",
  },
  {
    kanji: "校",
    on: "コウ, キョウ",
    meaning: "Exam, school, printing, proof, correction",
  },
  {
    kanji: "土",
    kun: "つち",
    on: "ド, ト",
    meaning: "Soil, earth, ground, Turkey",
  },
  {
    kanji: "木",
    kun: "き, こ-",
    on: "ボク, モク",
    meaning: "Tree, wood",
  },
  {
    kanji: "車",
    kun: "くるま",
    on: "シャ",
    meaning: "Car",
  },
  {
    kanji: "白",
    kun: "しろ, しら-, しろ. い",
    on: "ハク, ビャク",
    meaning: "White",
  },
  {
    kanji: "天",
    kun: "あまつ, あめ, あま-",
    on: "テン",
    meaning: "Heavens, sky, imperial",
  },
  {
    kanji: "火",
    kun: "ひ, -び, ほ-",
    on: "カ",
    meaning: "Fire",
  },
  {
    kanji: "右",
    kun: "みぎ",
    on: "ウ, ユウ",
    meaning: "Right",
  },
  {
    kanji: "左",
    kun: "ひだり",
    on: "サ, シャ",
    meaning: "Left",
  },
  {
    kanji: "休",
    kun: "やす. む, やす. まる, やす. める",
    on: "キュウ",
    meaning: "Rest, day off, retire, sleep",
  },
  {
    kanji: "立",
    kun: "た. つ, -た. つ, た. ち-, た. てる, -た. てる",
    on: "リツ, リュウ, リットル",
    meaning: "Stand up",
  },
  {
    kanji: "手",
    kun: "て, て-, -て, た-",
    on: "シュ, ズ",
    meaning: "Hand",
  },
  {
    kanji: "力",
    kun: "ちから",
    on: "リョク, リキ, リイ",
    meaning: "Power, strong, strain, bear up, exert",
  },
  {
    kanji: "目",
    kun: "め, -め, ま-",
    on: "モク, ボク",
    meaning: "Eye, class, look, insight, experience, care, favor",
  },
  {
    kanji: "田",
    kun: "た",
    on: "デン",
    meaning: "Rice field, rice paddy",
  },
  {
    kanji: "正",
    kun: "ただ. しい, ただ. す, まさ, まさ. に",
    on: "セイ, ショウ",
    meaning: "Correct, justice, righteous",
  },
  {
    kanji: "文",
    kun: "ふみ, あや",
    on: "ブン, モン",
    meaning: "Sentence, literature, style, art, decoration, figures, plan",
  },
  {
    kanji: "口",
    kun: "くち",
    on: "コウ, ク",
    meaning: "Mouth",
  },
  {
    kanji: "町",
    kun: "まち",
    on: "チョウ",
    meaning: "Town, village, block, street",
  },
  {
    kanji: "空",
    kun: "そら, あ. く, あ. き, あ. ける, から, す. く",
    on: "クウ",
    meaning: "Empty, sky, void, vacant, vacuum",
  },
  {
    kanji: "雨",
    kun: "あめ, あま-, -さめ",
    on: "ウ",
    meaning: "Rain",
  },
  {
    kanji: "足",
    kun: "あし, た. りる, た. る, た. す",
    on: "ソク",
    meaning: "Leg, foot, be sufficient, counter for pairs of footwear",
  },
  {
    kanji: "早",
    kun: "はや. い, はや, はや-, はや. まる, はや. める",
    on: "ソウ, サッ",
    meaning: "Early, fast",
  },
  {
    kanji: "字",
    kun: "あざ, あざな, -な",
    on: "ジ",
    meaning: "Character, letter, word, section of village",
  },
  {
    kanji: "音",
    kun: "おと, ね",
    on: "オン, イン, -ノン",
    meaning: "Sound, noise",
  },
  {
    kanji: "花",
    kun: "はな",
    on: "カ, ケ",
    meaning: "Flower",
  },
  {
    kanji: "赤",
    kun: "あか, あか-, あか. い, あか. らむ, あか. ら める",
    on: "セキ, シャク",
    meaning: "Red",
  },
  {
    kanji: "青",
    kun: "あお, あお-, あお. い",
    on: "セイ, ショウ",
    meaning: "Blue, green",
  },
  {
    kanji: "村",
    kun: "むら",
    on: "ソン",
    meaning: "Village, town",
  },
  {
    kanji: "夕",
    kun: "ゆう",
    on: "セキ",
    meaning: "Evening",
  },
  {
    kanji: "石",
    kun: "いし",
    on: "セキ, シャク, コク",
    meaning: "Stone",
  },
  {
    kanji: "竹",
    kun: "たけ",
    on: "チク",
    meaning: "Bamboo",
  },
  {
    kanji: "森",
    kun: "もり",
    on: "シン",
    meaning: "Forest, woods",
  },
  {
    kanji: "林",
    kun: "はやし",
    on: "リン",
    meaning: "Grove, forest",
  },
  {
    kanji: "王",
    on: "オウ, -ノウ",
    meaning: "King, rule, magnate",
  },
  {
    kanji: "犬",
    kun: "いぬ, いぬ-",
    on: "ケン",
    meaning: "Dog",
  },
  {
    kanji: "玉",
    kun: "たま, たま-, -だま",
    on: "ギョク",
    meaning: "Jewel, ball",
  },
  {
    kanji: "草",
    kun: "くさ, くさ-, -ぐさ",
    on: "ソウ",
    meaning: "Grass, weeds, herbs, pasture, write, draft",
  },
  {
    kanji: "耳",
    kun: "みみ",
    on: "ジ",
    meaning: "Ear",
  },
  {
    kanji: "虫",
    kun: "むし",
    on: "チュウ, キ",
    meaning: "Insect, bug, temper",
  },
  {
    kanji: "糸",
    kun: "いと",
    on: "シ",
    meaning: "Thread",
  },
  {
    kanji: "貝",
    kun: "かい",
    on: "バイ",
    meaning: "Shellfish",
  },
];

export default Grade1;
