const Grade2 = [
  {
    kanji: "国",
    hiragana: "くに",
    katakana: "コク",
    english: "Country",
  },
  {
    kanji: "長",
    hiragana: "なが. い, おさ",
    katakana: "チョウ",
    english: "Long, leader",
  },
  {
    kanji: "時",
    hiragana: "とき, -どき",
    katakana: "ジ",
    english: "Time, hour",
  },
  {
    kanji: "行",
    hiragana: "い. く, ゆ. く, -ゆ. き, -ゆき, -い. き, -いき",
    katakana: "コウ, ギョウ, アン",
    english: "Going, journey",
  },
  {
    kanji: "分",
    hiragana: "わ. ける, わ. け, わ. かれる, わ. かる, わ. かつ",
    katakana: "ブン, フン, ブ",
    english:
      "Part, minute of time, segment, share, degree, one’s lot, duty, understand, know, rate, 1%, chances",
  },
  {
    kanji: "後",
    hiragana: "のち, うし. ろ, うしろ, あと, おく. れる",
    katakana: "ゴ, コウ",
    english: "Behind, back, later",
  },
  {
    kanji: "前",
    hiragana: "まえ, -まえ",
    katakana: "ゼン",
    english: "In front, before",
  },
  {
    kanji: "間",
    hiragana: "あいだ, ま, あい",
    katakana: "カン, ケン",
    english: "Interval, space",
  },
  {
    kanji: "東",
    hiragana: "ひがし",
    katakana: "トウ",
    english: "East",
  },
  {
    kanji: "今",
    hiragana: "いま",
    katakana: "コン, キン",
    english: "Now",
  },
  {
    kanji: "高",
    hiragana: "たか. い, たか, -だか, たか. まる, たか. める",
    katakana: "コウ",
    english: "Tall, high, expensive",
  },
  {
    kanji: "外",
    hiragana: "そと, ほか, はず. す, はず. れる, と-",
    katakana: "ガイ, ゲ",
    english: "Outside",
  },
  {
    kanji: "来",
    hiragana: "く. る, きた. る, きた. す, き. たす, き. たる, き",
    katakana: "ライ, タイ",
    english: "Come, due, next, cause, become",
  },
  {
    kanji: "話",
    hiragana: "はな. す, はなし",
    katakana: "ワ",
    english: "Tale, talk",
  },
  {
    kanji: "北",
    hiragana: "きた",
    katakana: "ホク",
    english: "North",
  },
  {
    kanji: "午",
    hiragana: "うま",
    katakana: "ゴ",
    english:
      "Noon, sign of the horse, 11AM to 1PM, seventh sign of Chinese zodiac",
  },
  {
    kanji: "書",
    hiragana: "か. く, -が. き, -がき",
    katakana: "ショ",
    english: "Write",
  },
  {
    kanji: "半",
    hiragana: "なか. ば",
    katakana: "ハン",
    english: "Half, middle, odd number, semi, part",
  },
  {
    kanji: "西",
    hiragana: "にし",
    katakana: "セイ, サイ, ス",
    english: "West, Spain",
  },
  {
    kanji: "電",
    hiragana: "---",
    katakana: "デン",
    english: "Electricity",
  },
  {
    kanji: "語",
    hiragana: "かた. る, かた. らう",
    katakana: "ゴ",
    english: "Word, speech, language",
  },
  {
    kanji: "聞",
    hiragana: "き. く, き. こえる",
    katakana: "ブン, モン",
    english: "Hear, ask, listen",
  },
  {
    kanji: "食",
    hiragana: "く. う, く. らう, た. べる, は. む",
    katakana: "ショク, ジキ",
    english: "Eat, food",
  },
  {
    kanji: "何",
    hiragana: "なに, なん, なに-, なん-",
    katakana: "カ",
    english: "What",
  },
  {
    kanji: "南",
    hiragana: "みなみ",
    katakana: "ナン, ナ",
    english: "South",
  },
  {
    kanji: "万",
    hiragana: "よろず",
    katakana: "マン, バン",
    english: "Ten thousand, 10.000",
  },
  {
    kanji: "毎",
    hiragana: "ごと, -ごと. に",
    katakana: "マイ",
    english: "Every",
  },
  {
    kanji: "母",
    hiragana: "はは, も",
    katakana: "ボ",
    english: "Mom, mother",
  },
  {
    kanji: "読",
    hiragana: "よ. む, -よ. み",
    katakana: "ドク, トク, トウ",
    english: "Read",
  },
  {
    kanji: "友",
    hiragana: "とも",
    katakana: "ユウ",
    english: "Friend",
  },
  {
    kanji: "会",
    hiragana: "あ. う, あ. わせる, あつ. まる",
    katakana: "カイ, エ",
    english: "Meeting, meet, party, association, interview, join",
  },
  {
    kanji: "同",
    hiragana: "おな. じ",
    katakana: "ドウ",
    english: "Same, agree, equal",
  },
  {
    kanji: "自",
    hiragana: "みずか. ら, おの. ずから, おの. ずと",
    katakana: "ジ, シ",
    english: "Oneself",
  },
  {
    kanji: "社",
    hiragana: "やしろ",
    katakana: "シャ",
    english: "Company, firm, office, association, shrine",
  },
  {
    kanji: "父",
    hiragana: "ちち",
    katakana: "フ",
    english: "Father",
  },
  {
    kanji: "地",
    hiragana: "---",
    katakana: "チ, ジ",
    english: "Ground, earth",
  },
  {
    kanji: "方",
    hiragana: "かた, -かた, -がた",
    katakana: "ホウ",
    english: "Direction, person, alternative",
  },
  {
    kanji: "新",
    hiragana: "あたら. しい, あら. た, あら-, にい-",
    katakana: "シン",
    english: "New",
  },
  {
    kanji: "場",
    hiragana: "ば",
    katakana: "ジョウ, チョウ",
    english: "Location, place",
  },
  {
    kanji: "明",
    hiragana: "あ. かり, あか. るい, あか. るむ, あか. らむ",
    katakana: "メイ, ミョウ, ミン",
    english: "Bright, light",
  },
  {
    kanji: "京",
    hiragana: "みやこ",
    katakana: "キョウ, ケイ, キン",
    english: "Capital",
  },
  {
    kanji: "通",
    hiragana: "とお. る, とお. り, -とお. り, -どお. り, とお. す",
    katakana: "ツウ, ツ",
    english:
      "Traffic, pass through, avenue, commute, counter for letters, notes, documents, etc.",
  },
  {
    kanji: "言",
    hiragana: "い. う, こと",
    katakana: "ゲン, ゴン",
    english: "Say",
  },
  {
    kanji: "理",
    hiragana: "ことわり",
    katakana: "リ",
    english: "Logic, arrangement, reason, justice, truth",
  },
  {
    kanji: "体",
    hiragana: "からだ, かたち",
    katakana: "タイ, テイ",
    english: "Body, substance, object, reality, counter for images",
  },
  {
    kanji: "作",
    hiragana: "つく. る, つく. り, -づく. り",
    katakana: "サク, サ",
    english: "Make, production, prepare, build",
  },
  {
    kanji: "用",
    hiragana: "もち. いる",
    katakana: "ヨウ",
    english: "Utilize, business, service, use, employ",
  },
  {
    kanji: "強",
    hiragana: "つよ. い, つよ. まる, つよ. める, し. いる, こわ. い",
    katakana: "キョウ, ゴウ",
    english: "Strong",
  },
  {
    kanji: "公",
    hiragana: "おおやけ",
    katakana: "コウ, ク",
    english: "Public, prince, official, governmental",
  },
  {
    kanji: "野",
    hiragana: "の, の-",
    katakana: "ヤ, ショ",
    english: "Plains, field, rustic, civilian life",
  },
  {
    kanji: "思",
    hiragana: "おも. う, おもえら. く, おぼ. す",
    katakana: "シ",
    english: "Think",
  },
  {
    kanji: "家",
    hiragana: "いえ, や, うち",
    katakana: "カ, ケ",
    english: "House, home",
  },
  {
    kanji: "多",
    hiragana: "おお. い, まさ. に, まさ. る",
    katakana: "タ",
    english: "Many, frequent, much",
  },
  {
    kanji: "心",
    hiragana: "こころ, -ごころ",
    katakana: "シン",
    english: "Heart, mind, spirit",
  },
  {
    kanji: "教",
    hiragana: "おし. える, おそ. わる",
    katakana: "キョウ",
    english: "Teach, faith, doctrine",
  },
  {
    kanji: "元",
    hiragana: "もと",
    katakana: "ゲン, ガン",
    english: "Beginning, former time, origin",
  },
  {
    kanji: "近",
    hiragana: "ちか. い",
    katakana: "キン, コン",
    english: "Near, early, akin, tantamount",
  },
  {
    kanji: "考",
    hiragana: "かんが. える, かんが. え",
    katakana: "コウ",
    english: "Consider, think over",
  },
  {
    kanji: "画",
    hiragana: "えが. く, かく. する, かぎ. る, はかりごと, はか. る",
    katakana: "ガ, カク, エ, カイ",
    english: "Brush stroke, picture",
  },
  {
    kanji: "海",
    hiragana: "うみ",
    katakana: "カイ",
    english: "Sea, ocean",
  },
  {
    kanji: "売",
    hiragana: "う. る, う. れる",
    katakana: "バイ",
    english: "Sell",
  },
  {
    kanji: "知",
    hiragana: "し. る, し. らせる",
    katakana: "チ",
    english: "Know, wisdom",
  },
  {
    kanji: "道",
    hiragana: "みち",
    katakana: "ドウ, トウ",
    english: "Roadway, street, district, journey, course, moral, teachings",
  },
  {
    kanji: "計",
    hiragana: "はか. る, はか. らう",
    katakana: "ケイ",
    english: "Plot, plan, scheme, measure",
  },
  {
    kanji: "朝",
    hiragana: "あさ",
    katakana: "チョウ",
    english: "Morning, dynasty, regime, epoch, period, (North) Korea",
  },
  {
    kanji: "台",
    hiragana: "うてな, われ, つかさ",
    katakana: "ダイ, タイ",
    english: "Pedestal, a stand, counter for machines and vehicles",
  },
  {
    kanji: "広",
    hiragana: "ひろ. い, ひろ. まる, ひろ. める, ひろ. がる",
    katakana: "コウ",
    english: "Wide, broad, spacious",
  },
  {
    kanji: "少",
    hiragana: "すく. ない, すこ. し",
    katakana: "ショウ",
    english: "Few, little",
  },
  {
    kanji: "工",
    hiragana: "---",
    katakana: "コウ, ク, グ",
    english: "Craft, construction, katakana e",
  },
  {
    kanji: "止",
    hiragana: "と. まる, -ど. まり, と. める, -と. める, -ど. め",
    katakana: "シ",
    english: "Stop, halt",
  },
  {
    kanji: "切",
    hiragana: "き. る, -き. る, き. り, -き. り, -ぎ. り",
    katakana: "セツ, サイ",
    english: "Cut, cutoff, be sharp",
  },
  {
    kanji: "楽",
    hiragana: "たの. しい, たの. しむ, この. むガク, ラク, ゴウ",
    katakana: "ガク, ラク, ゴウ",
    english: "Music, comfort, ease",
  },
  {
    kanji: "店",
    hiragana: "みせ, たな",
    katakana: "テン",
    english: "Store, shop",
  },
  {
    kanji: "親",
    hiragana: "おや, おや-, した. しい, した. しむ",
    katakana: "シン",
    english: "Parent, intimacy, relative, familiarity, dealer (cards)",
  },
  {
    kanji: "答",
    hiragana: "こた. える, こた. え",
    katakana: "トウ",
    english: "Solution, answer",
  },
  {
    kanji: "夜",
    hiragana: "よ, よる",
    katakana: "ヤ",
    english: "Night, evening",
  },
  {
    kanji: "帰",
    hiragana: "かえ. る, かえ. す, おく. る, とつ. ぐ",
    katakana: "キ",
    english: "Homecoming, arrive at, lead to, result in",
  },
  {
    kanji: "古",
    hiragana: "ふる. い, ふる-, -ふる. す",
    katakana: "コ",
    english: "Old",
  },
  {
    kanji: "歌",
    hiragana: "うた, うた. う",
    katakana: "カ",
    english: "Song, sing",
  },
  {
    kanji: "買",
    hiragana: "か. う",
    katakana: "バイ",
    english: "Buy",
  },
  {
    kanji: "図",
    hiragana: "え, はか. る",
    katakana: "ズ, ト",
    english: "Map, drawing, plan, unexpected, accidentally",
  },
  {
    kanji: "週",
    hiragana: "---",
    katakana: "シュウ",
    english: "Week",
  },
  {
    kanji: "室",
    hiragana: "むろ",
    katakana: "シツ",
    english: "Room, apartment, chamber, greenhouse, cellar",
  },
  {
    kanji: "歩",
    hiragana: "ある. く, あゆ. む",
    katakana: "ホ, ブ, フ",
    english: "Walk, counter for steps",
  },
  {
    kanji: "風",
    hiragana: "かぜ, かざ-, -かぜ",
    katakana: "フウ, フ",
    english: "Wind, air, style, manner",
  },
  {
    kanji: "紙",
    hiragana: "かみ",
    katakana: "シ",
    english: "Paper",
  },
  {
    kanji: "黒",
    hiragana: "くろ, くろ. ずむ, くろ. い",
    katakana: "コク",
    english: "Black",
  },
  {
    kanji: "春",
    hiragana: "はる",
    katakana: "シュン",
    english: "Springtime, spring (season)",
  },
  {
    kanji: "色",
    hiragana: "いろ",
    katakana: "ショク, シキ",
    english: "Color",
  },
  {
    kanji: "走",
    hiragana: "はし. る",
    katakana: "ソウ",
    english: "Run",
  },
];

export default Grade2;
