const Grade1 = [
  {
    kanji: "日",
    hiragana: "ひ, -び, -か",
    katakana: "ニチ, ジツ",
    english: "day, sun, Japan, counter for days",
  },
  {
    kanji: "一",
    hiragana: "ひと-, ひと. つ",
    katakana: "イチ, イツ",
    english: "One",
  },
  {
    kanji: "人",
    hiragana: "ひと, -り, つ",
    katakana: "ジン, ニン",
    english: "Person",
  },
  {
    kanji: "年",
    hiragana: "とし",
    katakana: "ネン",
    english: "Year, counter for years",
  },
  {
    kanji: "大",
    hiragana: "おお-, おお. きい, -おお. いに",
    katakana: "ダイ, タイ",
    english: "Large, big",
  },
  {
    kanji: "十",
    hiragana: "とお, と",
    katakana: "ジュウ, ジッ, ジュッ",
    english: "Ten",
  },
  {
    kanji: "二",
    hiragana: "ふた, ふた. つ, ふたた. び",
    katakana: "ニ, ジ",
    english: "Two",
  },
  {
    kanji: "本",
    hiragana: "もと",
    katakana: "ホン",
    english:
      "book, present, main, true, real, counter for long cylindrical things",
  },
  {
    kanji: "中",
    hiragana: "なか, うち, あた. る",
    katakana: "チュウ",
    english: "in, inside, middle, mean, center",
  },
  {
    kanji: "出",
    hiragana: "で. る, -で, だ. す, -だ. す, い. でる, い. だす",
    katakana: "シュツ, スイ",
    english: "Exit, leave",
  },
  {
    kanji: "三",
    hiragana: "み, み. つ, みっ. つ",
    katakana: "サン, ゾウ",
    english: "Three",
  },
  {
    kanji: "見",
    hiragana: "み. る, み. える, み. せる",
    katakana: "ケン",
    english: "See, hopes, chances, idea, opinion, look at, visible",
  },
  {
    kanji: "月",
    hiragana: "つき",
    katakana: "ゲツ, ガツ",
    english: "Month, moon",
  },
  {
    kanji: "生",
    hiragana: "い. きる, い. かす, い. ける, う. まれる, う. まれ",
    katakana: "セイ, ショウ",
    english: "Life, genuine, birth",
  },
  {
    kanji: "五",
    hiragana: "いつ, いつ. つ",
    katakana: "ゴ",
    english: "Five",
  },
  {
    kanji: "上",
    hiragana: "うえ, -うえ, うわ-, かみ, あ. げる, -あ. げる",
    katakana: "ジョウ, ショウ, シャン",
    english: "Above, up",
  },
  {
    kanji: "四",
    hiragana: "よ, よ. つ, よっ. つ, よん",
    katakana: "シ",
    english: "Four",
  },
  {
    kanji: "金",
    hiragana: "かね, かな-, -がね",
    katakana: "キン, コン, ゴン",
    english: "Gold",
  },
  {
    kanji: "九",
    hiragana: "ここの, ここの. つ",
    katakana: "キュウ, ク",
    english: "Nine",
  },
  {
    kanji: "入",
    hiragana: "い. る, -い. る, -い. り, い. れる, -い. れ",
    katakana: "ニュウ, ジュ",
    english: "Enter, insert",
  },
  {
    kanji: "学",
    hiragana: "まな. ぶ",
    katakana: "ガク",
    english: "Study, learning, science",
  },
  {
    kanji: "円",
    hiragana: "まる. い, まる, まど, まど. か, まろ. やか",
    katakana: "エン",
    english: "Circle, yen, round",
  },
  {
    kanji: "子",
    hiragana: "こ, -こ, ね",
    katakana: "シ, ス, ツ",
    english: "Child, 11PM to 1AM, first sign of Chinese zodiac (Rat)",
  },
  {
    kanji: "八",
    hiragana: "や, や. つ, やっ. つ, よう",
    katakana: "ハチ",
    english: "Eight",
  },
  {
    kanji: "六",
    hiragana: "む, む. つ, むっ. つ, むい",
    katakana: "ロク, リク",
    english: "Six",
  },
  {
    kanji: "下",
    hiragana: "した, しも, もと, さ. げる, さ. がる, くだ. る",
    katakana: "カ, ゲ",
    english: "Below, down, descend, give, low, inferior",
  },
  {
    kanji: "気",
    hiragana: "いき",
    katakana: "キ, ケ",
    english: "Spirit, mind, air, atmosphere, mood",
  },
  {
    kanji: "小",
    hiragana: "ちい. さい, こ-, お-, さ-",
    katakana: "ショウ",
    english: "Little, small",
  },
  {
    kanji: "七",
    hiragana: "なな, なな. つ, なの",
    katakana: "シチ",
    english: "Seven",
  },
  {
    kanji: "山",
    hiragana: "やま",
    katakana: "サン, セン",
    english: "Mountain",
  },
  {
    kanji: "女",
    hiragana: "おんな, め",
    katakana: "ジョ, ニョ, ニョウ",
    english: "Woman, female",
  },
  {
    kanji: "百",
    hiragana: "もも",
    katakana: "ヒャク, ビャク",
    english: "Hundred",
  },
  {
    kanji: "先",
    hiragana: "さき, ま. ず",
    katakana: "セン",
    english: "Before, ahead, previous, future, precedence",
  },
  {
    kanji: "名",
    hiragana: "な, -な",
    katakana: "メイ, ミョウ",
    english: "Name, noted, distinguished, reputation",
  },
  {
    kanji: "川",
    hiragana: "かわ",
    katakana: "セン",
    english: "stream, river",
  },
  {
    kanji: "千",
    hiragana: "ち",
    katakana: "セン",
    english: "Thousand",
  },
  {
    kanji: "水",
    hiragana: "みず, みず-",
    katakana: "スイ",
    english: "Water",
  },
  {
    kanji: "男",
    hiragana: "おとこ, お",
    katakana: "ダン, ナン",
    english: "Male",
  },
  {
    kanji: "校",
    hiragana: "---",
    katakana: "コウ, キョウ",
    english: "Exam, school, printing, proof, correction",
  },
  {
    kanji: "土",
    hiragana: "つち",
    katakana: "ド, ト",
    english: "Soil, earth, ground, Turkey",
  },
  {
    kanji: "木",
    hiragana: "き, こ-",
    katakana: "ボク, モク",
    english: "Tree, wood",
  },
  {
    kanji: "車",
    hiragana: "くるま",
    katakana: "シャ",
    english: "Car",
  },
  {
    kanji: "白",
    hiragana: "しろ, しら-, しろ. い",
    katakana: "ハク, ビャク",
    english: "White",
  },
  {
    kanji: "天",
    hiragana: "あまつ, あめ, あま-",
    katakana: "テン",
    english: "Heavens, sky, imperial",
  },
  {
    kanji: "火",
    hiragana: "ひ, -び, ほ-",
    katakana: "カ",
    english: "Fire",
  },
  {
    kanji: "右",
    hiragana: "みぎ",
    katakana: "ウ, ユウ",
    english: "Right",
  },
  {
    kanji: "左",
    hiragana: "ひだり",
    katakana: "サ, シャ",
    english: "Left",
  },
  {
    kanji: "休",
    hiragana: "やす. む, やす. まる, やす. める",
    katakana: "キュウ",
    english: "Rest, day off, retire, sleep",
  },
  {
    kanji: "立",
    hiragana: "た. つ, -た. つ, た. ち-, た. てる, -た. てる",
    katakana: "リツ, リュウ, リットル",
    english: "Stand up",
  },
  {
    kanji: "手",
    hiragana: "て, て-, -て, た-",
    katakana: "シュ, ズ",
    english: "Hand",
  },
  {
    kanji: "力",
    hiragana: "ちから",
    katakana: "リョク, リキ, リイ",
    english: "Power, strong, strain, bear up, exert",
  },
  {
    kanji: "目",
    hiragana: "め, -め, ま-",
    katakana: "モク, ボク",
    english: "Eye, class, look, insight, experience, care, favor",
  },
  {
    kanji: "田",
    hiragana: "た",
    katakana: "デン",
    english: "Rice field, rice paddy",
  },
  {
    kanji: "正",
    hiragana: "ただ. しい, ただ. す, まさ, まさ. に",
    katakana: "セイ, ショウ",
    english: "Correct, justice, righteous",
  },
  {
    kanji: "文",
    hiragana: "ふみ, あや",
    katakana: "ブン, モン",
    english: "Sentence, literature, style, art, decoration, figures, plan",
  },
  {
    kanji: "口",
    hiragana: "くち",
    katakana: "コウ, ク",
    english: "Mouth",
  },
  {
    kanji: "町",
    hiragana: "まち",
    katakana: "チョウ",
    english: "Town, village, block, street",
  },
  {
    kanji: "空",
    hiragana: "そら, あ. く, あ. き, あ. ける, から, す. く",
    katakana: "クウ",
    english: "Empty, sky, void, vacant, vacuum",
  },
  {
    kanji: "雨",
    hiragana: "あめ, あま-, -さめ",
    katakana: "ウ",
    english: "Rain",
  },
  {
    kanji: "足",
    hiragana: "あし, た. りる, た. る, た. す",
    katakana: "ソク",
    english: "Leg, foot, be sufficient, counter for pairs of footwear",
  },
  {
    kanji: "早",
    hiragana: "はや. い, はや, はや-, はや. まる, はや. める",
    katakana: "ソウ, サッ",
    english: "Early, fast",
  },
  {
    kanji: "字",
    hiragana: "あざ, あざな, -な",
    katakana: "ジ",
    english: "Character, letter, word, section of village",
  },
  {
    kanji: "音",
    hiragana: "おと, ね",
    katakana: "オン, イン, -ノン",
    english: "Sound, noise",
  },
  {
    kanji: "花",
    hiragana: "はな",
    katakana: "カ, ケ",
    english: "Flower",
  },
  {
    kanji: "赤",
    hiragana: "あか, あか-, あか. い, あか. らむ, あか. ら める",
    katakana: "セキ, シャク",
    english: "Red",
  },
  {
    kanji: "青",
    hiragana: "あお, あお-, あお. い",
    katakana: "セイ, ショウ",
    english: "Blue, green",
  },
  {
    kanji: "村",
    hiragana: "むら",
    katakana: "ソン",
    english: "Village, town",
  },
  {
    kanji: "夕",
    hiragana: "ゆう",
    katakana: "セキ",
    english: "Evening",
  },
  {
    kanji: "石",
    hiragana: "いし",
    katakana: "セキ, シャク, コク",
    english: "Stone",
  },
  {
    kanji: "竹",
    hiragana: "たけ",
    katakana: "チク",
    english: "Bamboo",
  },
  {
    kanji: "森",
    hiragana: "もり",
    katakana: "シン",
    english: "Forest, woods",
  },
  {
    kanji: "林",
    hiragana: "はやし",
    katakana: "リン",
    english: "Grove, forest",
  },
  {
    kanji: "王",
    hiragana: "---",
    katakana: "オウ, -ノウ",
    english: "King, rule, magnate",
  },
  {
    kanji: "犬",
    hiragana: "いぬ, いぬ-",
    katakana: "ケン",
    english: "Dog",
  },
  {
    kanji: "玉",
    hiragana: "たま, たま-, -だま",
    katakana: "ギョク",
    english: "Jewel, ball",
  },
  {
    kanji: "草",
    hiragana: "くさ, くさ-, -ぐさ",
    katakana: "ソウ",
    english: "Grass, weeds, herbs, pasture, write, draft",
  },
  {
    kanji: "耳",
    hiragana: "みみ",
    katakana: "ジ",
    english: "Ear",
  },
  {
    kanji: "虫",
    hiragana: "むし",
    katakana: "チュウ, キ",
    english: "Insect, bug, temper",
  },
  {
    kanji: "糸",
    hiragana: "いと",
    katakana: "シ",
    english: "Thread",
  },
  {
    kanji: "貝",
    hiragana: "かい",
    katakana: "バイ",
    english: "Shellfish",
  },
];

export default Grade1;
