import React from "react";
import styled from "styled-components";
import Collapsible from "react-collapsible";

import GridSmall from "../styles/grid-small";
import Titles from "./styles/titles";

const CollapsibleCard = styled(GridSmall)`
  max-width: 600px;
  background: none;
  margin-bottom: 25px;
  opacity: 1;
`;

const NatureInfo = () => {
  return (
    <>
      {/* Convert to mapping */}
      <CollapsibleCard>
        <Titles>
          <div>
            <p>Animals and insects</p>
            <p>
              動物や虫
              <span>どうぶつやむし</span>
            </p>
          </div>
          <Collapsible trigger="Zoo">
            <table>
              <tr>
                <td>Zoo</td>
                <td>動物園</td>
                <td>どうぶつえん</td>
                <td>Dōbutsuen</td>
              </tr>
              <tr>
                <td>Turtle</td>
                <td>亀</td>
                <td>かめ</td>
                <td>Kame</td>
              </tr>
              <tr>
                <td>Elephant</td>
                <td>象</td>
                <td>ぞう</td>
                <td>Zō</td>
              </tr>
              <tr>
                <td>Giraffe</td>
                <td>&nbsp;</td>
                <td>キリン</td>
                <td>Girin</td>
              </tr>
              <tr>
                <td>Lion</td>
                <td>&nbsp;</td>
                <td>ライオン</td>
                <td>Raion</td>
              </tr>
              <tr>
                <td>Tiger</td>
                <td>虎</td>
                <td>とら</td>
                <td>Tora</td>
              </tr>
              <tr>
                <td>Penguin</td>
                <td>&nbsp;</td>
                <td>ペンギン</td>
                <td>Pengin</td>
              </tr>
              <tr>
                <td>Snake</td>
                <td>&nbsp;</td>
                <td>ヘビ</td>
                <td>Hebi</td>
              </tr>
              <tr>
                <td>Fox</td>
                <td>狐</td>
                <td>きつね</td>
                <td>Kitsune</td>
              </tr>
            </table>
          </Collapsible>
          <Collapsible trigger="Farm">
            <table>
              <tr>
                <td>Farm</td>
                <td>牧場</td>
                <td>ぼくじょう</td>
                <td>Bokujō</td>
              </tr>
              <tr>
                <td>Horse</td>
                <td>馬</td>
                <td>うま</td>
                <td>Uma</td>
              </tr>
              <tr>
                <td>Pig</td>
                <td>豚</td>
                <td>ぶた</td>
                <td>Buta</td>
              </tr>
              <tr>
                <td>Cow</td>
                <td>牛</td>
                <td>うし</td>
                <td>Ushi</td>
              </tr>
              <tr>
                <td>Chicken</td>
                <td>&nbsp;</td>
                <td>チキン</td>
                <td>Chikin</td>
              </tr>
              <tr>
                <td>Sheep</td>
                <td>羊</td>
                <td>ひつじ</td>
                <td>Hitsuji</td>
              </tr>
            </table>
          </Collapsible>
          <Collapsible trigger="Pets">
            <table>
              <tr>
                <td>Pets</td>
                <td>&nbsp;</td>
                <td>ペット</td>
                <td>Petto</td>
              </tr>
              <tr>
                <td>Dog</td>
                <td>犬</td>
                <td>いぬ</td>
                <td>Inu</td>
              </tr>
              <tr>
                <td>Puppy</td>
                <td>子犬</td>
                <td>こいぬ</td>
                <td>Koinu</td>
              </tr>
              <tr>
                <td>Cat</td>
                <td>猫</td>
                <td>ねこ</td>
                <td>Neko</td>
              </tr>
              <tr>
                <td>Kitten</td>
                <td>子猫</td>
                <td>こねこ</td>
                <td>Koneko</td>
              </tr>
              <tr>
                <td>Hamster</td>
                <td>&nbsp;</td>
                <td>ハムスター</td>
                <td>Hamstā</td>
              </tr>
              <tr>
                <td>Bird</td>
                <td>鳥</td>
                <td>とり</td>
                <td>Tori</td>
              </tr>
            </table>
          </Collapsible>
          <Collapsible trigger="Aquatic">
            <table>
              <tr>
                <td>Aquatic</td>
                <td>水生</td>
                <td>すいせい</td>
                <td>Suisē</td>
              </tr>
              <tr>
                <td>Fish</td>
                <td>魚</td>
                <td>さかな</td>
                <td>Sakana</td>
              </tr>
              <tr>
                <td>Whale</td>
                <td>鯨</td>
                <td>くじら</td>
                <td>Kujira</td>
              </tr>
              <tr>
                <td>Dolphin</td>
                <td>海豚</td>
                <td>いるか</td>
                <td>Iruka</td>
              </tr>
              <tr>
                <td>Crab</td>
                <td>&nbsp;</td>
                <td>カニ</td>
                <td>Kani</td>
              </tr>
              <tr>
                <td>Shark</td>
                <td>鮫</td>
                <td>さめ</td>
                <td>Same</td>
              </tr>
              <tr>
                <td>Starfish</td>
                <td>海星</td>
                <td>ひとで</td>
                <td>Hitode</td>
              </tr>
              <tr>
                <td>Octopus</td>
                <td>蛸</td>
                <td>たこ</td>
                <td>Tako</td>
              </tr>
            </table>
          </Collapsible>
          <Collapsible trigger="Insects">
            <table>
              <tr>
                <td>Insect</td>
                <td>虫</td>
                <td>むし</td>
                <td>Mushi</td>
              </tr>
              <tr>
                <td>Bee</td>
                <td>蜂</td>
                <td>はち</td>
                <td>Hachi</td>
              </tr>
              <tr>
                <td>Beetle</td>
                <td>甲虫</td>
                <td>かぶとむし</td>
                <td>Kabutomushi</td>
              </tr>
              <tr>
                <td>Black fly</td>
                <td>蚋</td>
                <td>ぶゆ</td>
                <td>Buyu</td>
              </tr>
              <tr>
                <td>Butterfly</td>
                <td>&nbsp;</td>
                <td>バタフライ</td>
                <td>Batafurai</td>
              </tr>
              <tr>
                <td>Ant</td>
                <td>蟻</td>
                <td>あり</td>
                <td>Ari</td>
              </tr>
              <tr>
                <td>Larva</td>
                <td>幼虫</td>
                <td>ようちゅう</td>
                <td>Yōchū</td>
              </tr>
              <tr>
                <td>Spider</td>
                <td>蜘蛛</td>
                <td>くも</td>
                <td>Kumo</td>
              </tr>
            </table>
          </Collapsible>
        </Titles>
      </CollapsibleCard>

      <CollapsibleCard>
        <Titles>
          <div>
            <p>Plants and other things</p>
            <p>
              草木や他のもの
              <span>くさきやほかのもの</span>
            </p>
          </div>
          <Collapsible trigger="Land">
            <table>
              <tr>
                <td>Land</td>
                <td>地</td>
                <td>ち</td>
                <td>Chi</td>
              </tr>
              <tr>
                <td>Tree</td>
                <td>木</td>
                <td>き</td>
                <td>Ki</td>
              </tr>
              <tr>
                <td>Flower</td>
                <td>花</td>
                <td>はな</td>
                <td>Hana</td>
              </tr>
              <tr>
                <td>Grass</td>
                <td>草</td>
                <td>くさ</td>
                <td>Kusa</td>
              </tr>
              <tr>
                <td>Boulder</td>
                <td>岩</td>
                <td>いわ</td>
                <td>Iwa</td>
              </tr>
              <tr>
                <td>Bush</td>
                <td>&nbsp;</td>
                <td>ブッシュ</td>
                <td>Busshu</td>
              </tr>
              <tr>
                <td>Mountain</td>
                <td>山</td>
                <td>やま</td>
                <td>Yama</td>
              </tr>
              <tr>
                <td>Rice field</td>
                <td>田</td>
                <td>た</td>
                <td>Ta</td>
              </tr>
              <tr>
                <td>River</td>
                <td>川</td>
                <td>かわ</td>
                <td>Kawa</td>
              </tr>
            </table>
          </Collapsible>
          <Collapsible trigger="Sea">
            <table>
              <tr>
                <td>Sea</td>
                <td>海</td>
                <td>うみ</td>
                <td>Umi</td>
              </tr>
              <tr>
                <td>Seaweed</td>
                <td>海草</td>
                <td>かいそう</td>
                <td>Kaisō</td>
              </tr>
              <tr>
                <td>Coral reef</td>
                <td>サンゴ礁</td>
                <td>さんごしょう</td>
                <td>Sangoshō</td>
              </tr>
            </table>
          </Collapsible>
        </Titles>
      </CollapsibleCard>

      <CollapsibleCard>
        <Titles>
          <div>
            <p>Food</p>
            <p>
              食べ物
              <span>たべもの</span>
            </p>
          </div>
          <Collapsible trigger="Vegetables">
            <table>
              <tr>
                <td>Vegetables</td>
                <td>野菜</td>
                <td>やさい</td>
                <td>Yasai</td>
              </tr>
              <tr>
                <td>Welsh onion</td>
                <td>葱</td>
                <td>ねぎ</td>
                <td>Negi</td>
              </tr>
              <tr>
                <td>Potato</td>
                <td>じゃが芋</td>
                <td>じゃがいも</td>
                <td>Jagaimo</td>
              </tr>
              <tr>
                <td>Pumpkin</td>
                <td>南瓜</td>
                <td>かぼちゃ</td>
                <td>Kabocha</td>
              </tr>
              <tr>
                <td>White raddish</td>
                <td>大根</td>
                <td>だいこん</td>
                <td>Daikon</td>
              </tr>
              <tr>
                <td>Tomato</td>
                <td>&nbsp;</td>
                <td>トマト</td>
                <td>Tomato</td>
              </tr>
              <tr>
                <td>Corn</td>
                <td>穀物</td>
                <td>こくもつ</td>
                <td>Kokumotsu</td>
              </tr>
              <tr>
                <td>Carrot</td>
                <td>人参</td>
                <td>にんじん</td>
                <td>Ninjin</td>
              </tr>
              <tr>
                <td>Bell pepper</td>
                <td>&nbsp;</td>
                <td>ピーマン</td>
                <td>Pīman</td>
              </tr>
            </table>
          </Collapsible>
          <Collapsible trigger="Fruits">
            <table>
              <tr>
                <td>Fruit</td>
                <td>果物</td>
                <td>くだもの</td>
                <td>Kudamono</td>
              </tr>
              <tr>
                <td>Pear</td>
                <td>梨</td>
                <td>なし</td>
                <td>Nashi</td>
              </tr>
              <tr>
                <td>Apple</td>
                <td>林檎</td>
                <td>りんご</td>
                <td>Ringo</td>
              </tr>
              <tr>
                <td>Banana</td>
                <td>&nbsp;</td>
                <td>バナナ</td>
                <td>Banana</td>
              </tr>
              <tr>
                <td>Peach</td>
                <td>桃</td>
                <td>もも</td>
                <td>Momo</td>
              </tr>
              <tr>
                <td>Melon</td>
                <td>&nbsp;</td>
                <td>メロン</td>
                <td>Meron</td>
              </tr>
              <tr>
                <td>Kiwi</td>
                <td>&nbsp;</td>
                <td>キウイ</td>
                <td>Kiui</td>
              </tr>
              <tr>
                <td>Grapes</td>
                <td>葡萄</td>
                <td>ぶどう</td>
                <td>Budō</td>
              </tr>
            </table>
          </Collapsible>
          <Collapsible trigger="Meat">
            <table>
              <tr>
                <td>Meat</td>
                <td>肉</td>
                <td>にく</td>
                <td>Niku</td>
              </tr>
              <tr>
                <td>Steak</td>
                <td>&nbsp;</td>
                <td>ステーキ</td>
                <td>Sutēki</td>
              </tr>
              <tr>
                <td>Pork</td>
                <td>豚肉</td>
                <td>ぶたにく</td>
                <td>Butaniku</td>
              </tr>
              <tr>
                <td>Beef</td>
                <td>牛肉</td>
                <td>ぎゅうにく</td>
                <td>Gyūniku</td>
              </tr>
              <tr>
                <td>Fish meat</td>
                <td>魚肉</td>
                <td>ぎょにく</td>
                <td>Gyoniku</td>
              </tr>
            </table>
          </Collapsible>
        </Titles>
      </CollapsibleCard>

      <CollapsibleCard>
        <Titles>
          <div>
            <p>Colors</p>
            <p>
              色<span>いろ</span>
            </p>
          </div>
          <Collapsible trigger="Rainbow">
            <table>
              <tr>
                <td>Rainbow</td>
                <td>虹</td>
                <td>にじ</td>
                <td>Niji</td>
              </tr>
              <tr>
                <td>Red</td>
                <td>赤</td>
                <td>あか</td>
                <td>Aka</td>
              </tr>
              <tr>
                <td>Orange</td>
                <td>橙色</td>
                <td>だいだいいろ</td>
                <td>Daidaiiro</td>
              </tr>
              <tr>
                <td>Yellow</td>
                <td>黄色</td>
                <td>きいろ</td>
                <td>Kiiro</td>
              </tr>
              <tr>
                <td>Green</td>
                <td>緑</td>
                <td>みどり</td>
                <td>Midori</td>
              </tr>
              <tr>
                <td>Blue</td>
                <td>青</td>
                <td>あお</td>
                <td>Ao</td>
              </tr>
              <tr>
                <td>Purple</td>
                <td>紫</td>
                <td>むらさき</td>
                <td>Murasaki</td>
              </tr>
              <tr>
                <td>Pink</td>
                <td>桃色</td>
                <td>ももいろ</td>
                <td>Momoiro</td>
              </tr>
            </table>
          </Collapsible>
          <Collapsible trigger="Other">
            <table>
              <tr>
                <td>Brown</td>
                <td>茶色</td>
                <td>ちゃいろ</td>
                <td>Chairo</td>
              </tr>
              <tr>
                <td>Gold</td>
                <td>金</td>
                <td>きん</td>
                <td>Kin</td>
              </tr>
              <tr>
                <td>Silver</td>
                <td>銀</td>
                <td>ぎん</td>
                <td>Gin</td>
              </tr>
              <tr>
                <td>Black</td>
                <td>黒</td>
                <td>くろ</td>
                <td>Kuro</td>
              </tr>
              <tr>
                <td>Grey</td>
                <td>灰色</td>
                <td>はいいろ</td>
                <td>Haiiro</td>
              </tr>
              <tr>
                <td>White</td>
                <td>白</td>
                <td>しろ</td>
                <td>Shiro</td>
              </tr>
            </table>
          </Collapsible>
        </Titles>
      </CollapsibleCard>
    </>
  );
};

export default NatureInfo;
