const hiragana = [
  {
    consonant: "n",
    hirlettera: "ん",
    hirletteri: " ",
    hirletteru: " ",
    hirlettere: " ",
    hirlettero: " ",
  },
  {
    consonant: "w-",
    hirlettera: "わ",
    hirletteri: " ",
    hirletteru: " ",
    hirlettere: " ",
    hirlettero: "を",
  },
  {
    consonant: "r-",
    hirlettera: "ら",
    hirletteri: "り",
    hirletteru: "る",
    hirlettere: "れ",
    hirlettero: "ろ",
  },
  {
    consonant: "y-",
    hirlettera: "や",
    hirletteri: " ",
    hirletteru: "ゆ",
    hirlettere: " ",
    hirlettero: "よ",
  },
  {
    consonant: "m-",
    hirlettera: "ま",
    hirletteri: "み",
    hirletteru: "む",
    hirlettere: "め",
    hirlettero: "も",
  },
  {
    consonant: "h-",
    hirlettera: "は",
    hirletteri: "ひ",
    hirletteru: "ふ",
    hirlettere: "へ",
    hirlettero: "ほ",
  },
  {
    consonant: "n-",
    hirlettera: "な",
    hirletteri: "に",
    hirletteru: "ぬ",
    hirlettere: "ね",
    hirlettero: "の",
  },
  {
    consonant: "t-",
    hirlettera: "た",
    hirletteri: "ち",
    hirletteru: "つ",
    hirlettere: "て",
    hirlettero: "と",
  },
  {
    consonant: "s-",
    hirlettera: "さ",
    hirletteri: "し",
    hirletteru: "す",
    hirlettere: "せ",
    hirlettero: "そ",
  },
  {
    consonant: "k-",
    hirlettera: "か",
    hirletteri: "き",
    hirletteru: "く",
    hirlettere: "け",
    hirlettero: "こ",
  },
  {
    consonant: " ",
    hirlettera: "あ",
    hirletteri: "い",
    hirletteru: "う",
    hirlettere: "え",
    hirlettero: "お",
  },
  {
    consonant: " ",
    vowela: "-a",
    voweli: "-i",
    vowelu: "-u",
    vowele: "-e",
    vowelo: "-o",
  },
];

export default hiragana;
