const katakana = [
  {
    consonant: "n",
    hirlettera: "ン",
    hirletteri: " ",
    hirletteru: " ",
    hirlettere: " ",
    hirlettero: " ",
  },
  {
    consonant: "w-",
    hirlettera: "ワ",
    hirletteri: " ",
    hirletteru: " ",
    hirlettere: " ",
    hirlettero: "ヲ",
  },
  {
    consonant: "r-",
    hirlettera: "ラ",
    hirletteri: "リ",
    hirletteru: "ル",
    hirlettere: "レ",
    hirlettero: "ロ",
  },
  {
    consonant: "y-",
    hirlettera: "ヤ",
    hirletteri: " ",
    hirletteru: "ユ",
    hirlettere: " ",
    hirlettero: "ヨ",
  },
  {
    consonant: "m-",
    hirlettera: "マ",
    hirletteri: "ミ",
    hirletteru: "ム",
    hirlettere: "メ",
    hirlettero: "モ",
  },
  {
    consonant: "h-",
    hirlettera: "ハ",
    hirletteri: "ヒ",
    hirletteru: "フ",
    hirlettere: "ヘ",
    hirlettero: "ホ",
  },
  {
    consonant: "n-",
    hirlettera: "ナ",
    hirletteri: "ニ",
    hirletteru: "ヌ",
    hirlettere: "ネ",
    hirlettero: "ノ",
  },
  {
    consonant: "t-",
    hirlettera: "タ",
    hirletteri: "チ",
    hirletteru: "ツ",
    hirlettere: "テ",
    hirlettero: "ト",
  },
  {
    consonant: "s-",
    hirlettera: "サ",
    hirletteri: "シ",
    hirletteru: "ス",
    hirlettere: "セ",
    hirlettero: "ソ",
  },
  {
    consonant: "k-",
    hirlettera: "カ",
    hirletteri: "キ",
    hirletteru: "ク",
    hirlettere: "ケ",
    hirlettero: "コ",
  },
  {
    consonant: " ",
    hirlettera: "ア",
    hirletteri: "イ",
    hirletteru: "ウ",
    hirlettere: "エ",
    hirlettero: "オ",
  },
  {
    consonant: " ",
    vowela: "-a",
    voweli: "-i",
    vowelu: "-u",
    vowele: "-e",
    vowelo: "-o",
  },
];

export default katakana;
