const katakana = [
  {
    gojuon_romaji: '•',
    gojuon_a: 'ン',
    gojuon_romaji_a: 'n',
  },
  {
    gojuon_romaji: 'w-',
    gojuon_a: 'ワ',
    gojuon_romaji_a: 'wa',
    gojuon_o: 'ヲ',
    gojuon_romaji_o: 'wo',
  },
  {
    gojuon_romaji: 'r-',
    yoon_romaji: 'r-',
    gojuon_a: 'ラ',
    gojuon_romaji_a: 'ra',
    gojuon_i: 'リ',
    gojuon_romaji_i: 'ri',
    gojuon_u: 'ル',
    gojuon_romaji_u: 'ru',
    gojuon_e: 'レ',
    gojuon_romaji_e: 're',
    gojuon_o: 'ロ',
    gojuon_romaji_o: 'ro',
    yoon_1: 'リャ',
    yoon_romaji_1: 'rya',
    yoon_2: 'リュ',
    yoon_romaji_2: 'ryu',
    yoon_3: 'リョ',
    yoon_romaji_3: 'ryo',
  },
  {
    gojuon_romaji: 'y-',
    gojuon_a: 'ヤ',
    gojuon_romaji_a: 'ya',
    gojuon_u: 'ユ',
    gojuon_romaji_u: 'yu',
    gojuon_o: 'ヨ',
    gojuon_romaji_o: 'yo',
  },
  {
    gojuon_romaji: 'm-',
    yoon_romaji: 'm-',
    gojuon_a: 'マ',
    gojuon_romaji_a: 'ma',
    gojuon_i: 'ミ',
    gojuon_romaji_i: 'mi',
    gojuon_u: 'ム',
    gojuon_romaji_u: 'mu',
    gojuon_e: 'メ',
    gojuon_romaji_e: 'me',
    gojuon_o: 'モ',
    gojuon_romaji_o: 'mo',
    yoon_1: 'ミャ',
    yoon_romaji_1: 'mya',
    yoon_2: 'ミュ',
    yoon_romaji_2: 'myu',
    yoon_3: 'ミョ',
    yoon_romaji_3: 'myo',
  },
  {
    gojuon_romaji: 'h-',
    dakuon_romaji: 'b-',
    yoon_romaji: '*h-',
    handakuon_romaji: 'p-',
    gojuon_a: 'ハ',
    gojuon_romaji_a: 'ha',
    gojuon_i: 'ヒ',
    gojuon_romaji_i: 'hi',
    gojuon_u: 'フ',
    gojuon_romaji_u: 'fu',
    gojuon_e: 'ヘ',
    gojuon_romaji_e: 'he',
    gojuon_o: 'ホ',
    gojuon_romaji_o: 'ho',
    dakuon_a: 'バ',
    dakuon_romaji_a: 'ba',
    dakuon_i: 'ビ',
    dakuon_romaji_i: 'bi',
    dakuon_u: 'ブ',
    dakuon_romaji_u: 'bu',
    dakuon_e: 'ベ',
    dakuon_romaji_e: 'be',
    dakuon_o: 'ボ',
    dakuon_romaji_o: 'bo',
    handakuon_a: 'パ',
    handakuon_romaji_a: 'pa',
    handakuon_i: 'ピ',
    handakuon_romaji_i: 'pi',
    handakuon_u: 'プ',
    handakuon_romaji_u: 'pu',
    handakuon_e: 'ペ',
    handakuon_romaji_e: 'pe',
    handakuon_o: 'ポ',
    handakuon_romaji_o: 'po',
    yoon_1: 'ヒャ',
    yoon_romaji_1: 'hya',
    yoon_2: 'ヒュ',
    yoon_romaji_2: 'hyu',
    yoon_3: 'ヒョ',
    yoon_romaji_3: 'hyo',
    yoon_4: 'ビャ',
    yoon_romaji_4: 'bya',
    yoon_5: 'ビュ',
    yoon_romaji_5: 'byu',
    yoon_6: 'ビョ',
    yoon_romaji_6: 'byo',
    yoon_7: 'ピャ',
    yoon_romaji_7: 'pya',
    yoon_8: 'ピュ',
    yoon_romaji_8: 'pyu',
    yoon_9: 'ピョ',
    yoon_romaji_9: 'pyo',
  },
  {
    gojuon_romaji: 'n-',
    yoon_romaji: 'n-',
    gojuon_a: 'ナ',
    gojuon_romaji_a: 'na',
    gojuon_i: 'ニ',
    gojuon_romaji_i: 'ni',
    gojuon_u: 'ヌ',
    gojuon_romaji_u: 'nu',
    gojuon_e: 'ネ',
    gojuon_romaji_e: 'ne',
    gojuon_o: 'ノ',
    gojuon_romaji_o: 'no',
    yoon_1: 'ニャ',
    yoon_romaji_1: 'nya',
    yoon_2: 'ニュ',
    yoon_romaji_2: 'nyu',
    yoon_3: 'ニョ',
    yoon_romaji_3: 'nyo',
  },
  {
    gojuon_romaji: 't-',
    dakuon_romaji: 'd-',
    yoon_romaji: 'ch-',
    gojuon_a: 'タ',
    gojuon_romaji_a: 'ta',
    gojuon_i: 'チ',
    gojuon_romaji_i: 'chi',
    gojuon_u: 'ツ',
    gojuon_romaji_u: 'tsu',
    gojuon_e: 'テ',
    gojuon_romaji_e: 'te',
    gojuon_o: 'ト',
    gojuon_romaji_o: 'to',
    dakuon_a: 'ダ',
    dakuon_romaji_a: 'da',
    dakuon_i: 'ヂ',
    dakuon_romaji_i: 'ji',
    dakuon_u: 'ヅ',
    dakuon_romaji_u: 'zu',
    dakuon_e: 'デ',
    dakuon_romaji_e: 'de',
    dakuon_o: 'ド',
    dakuon_romaji_o: 'do',
    yoon_1: 'チャ',
    yoon_romaji_1: 'cha',
    yoon_2: 'チュ',
    yoon_romaji_2: 'chu',
    yoon_3: 'チョ',
    yoon_romaji_3: 'cho',
  },
  {
    gojuon_romaji: 's-',
    dakuon_romaji: 'z-',
    yoon_romaji: '*sh-',
    gojuon_a: 'サ',
    gojuon_romaji_a: 'sa',
    gojuon_i: 'シ',
    gojuon_romaji_i: 'shi',
    gojuon_u: 'ス',
    gojuon_romaji_u: 'su',
    gojuon_e: 'セ',
    gojuon_romaji_e: 'se',
    gojuon_o: 'ソ',
    gojuon_romaji_o: 'so',
    dakuon_a: 'ザ',
    dakuon_romaji_a: 'za',
    dakuon_i: 'ジ',
    dakuon_romaji_i: 'ji',
    dakuon_u: 'ズ',
    dakuon_romaji_u: 'zu',
    dakuon_e: 'ゼ',
    dakuon_romaji_e: 'ze',
    dakuon_o: 'ゾ',
    dakuon_romaji_o: 'zo',
    yoon_1: 'シャ',
    yoon_romaji_1: 'sha',
    yoon_2: 'シュ',
    yoon_romaji_2: 'shu',
    yoon_3: 'ショ',
    yoon_romaji_3: 'sho',
    yoon_4: 'ジャ',
    yoon_romaji_4: 'ja',
    yoon_5: 'ジュ',
    yoon_romaji_5: 'ju',
    yoon_6: 'ジョ',
    yoon_romaji_6: 'jo',
  },
  {
    gojuon_romaji: 'k-',
    dakuon_romaji: 'g-',
    yoon_romaji: '*k-',
    gojuon_a: 'カ',
    gojuon_romaji_a: 'ka',
    gojuon_i: 'キ',
    gojuon_romaji_i: 'ki',
    gojuon_u: 'ク',
    gojuon_romaji_u: 'ku',
    gojuon_e: 'ケ',
    gojuon_romaji_e: 'ke',
    gojuon_o: 'コ',
    gojuon_romaji_o: 'ko',
    dakuon_a: 'ガ',
    dakuon_romaji_a: 'ga',
    dakuon_i: 'ギ',
    dakuon_romaji_i: 'gi',
    dakuon_u: 'グ',
    dakuon_romaji_u: 'gu',
    dakuon_e: 'ゲ',
    dakuon_romaji_e: 'ge',
    dakuon_o: 'ゴ',
    dakuon_romaji_o: 'go',
    yoon_1: 'キャ',
    yoon_romaji_1: 'kya',
    yoon_2: 'キュ',
    yoon_romaji_2: 'kyu',
    yoon_3: 'キョ',
    yoon_romaji_3: 'kyo',
    yoon_4: 'ギャ',
    yoon_romaji_4: 'gya',
    yoon_5: 'ギュ',
    yoon_romaji_5: 'gyu',
    yoon_6: 'ギョ',
    yoon_romaji_6: 'gyo',
  },
  {
    gojuon_a: 'ア',
    gojuon_romaji_a: 'a',
    gojuon_i: 'イ',
    gojuon_romaji_i: 'i',
    gojuon_u: 'ウ',
    gojuon_romaji_u: 'u',
    gojuon_e: 'エ',
    gojuon_romaji_e: 'e',
    gojuon_o: 'オ',
    gojuon_romaji_o: 'o',
  },
  {
    gojuon_a: '-a',
    gojuon_i: '-i',
    gojuon_u: '-u',
    gojuon_e: '-e',
    gojuon_o: '-o',
    dakuon_a: '-a',
    dakuon_i: '-i',
    dakuon_u: '-u',
    dakuon_e: '-e',
    dakuon_o: '-o',
    handakuon_a: '-a',
    handakuon_i: '-i',
    handakuon_u: '-u',
    handakuon_e: '-e',
    handakuon_o: '-o',
    yoon_1: '-a',
    yoon_2: '-u',
    yoon_3: '-o',
    yoon_4: '-a',
    yoon_5: '-u',
    yoon_6: '-o',
    yoon_7: '-a',
    yoon_8: '-u',
    yoon_9: '-o',
  },
];

export default katakana;
